package postgres

import knowledgepostgres "github.com/markhuangai/dense-mem/internal/knowledge/postgres"

type CreateIngestInput = knowledgepostgres.CreateIngestInput
type EvidenceInput = knowledgepostgres.EvidenceInput
type EvidenceFragment = knowledgepostgres.EvidenceFragment
type ApplyRelationshipDecisionInput = knowledgepostgres.ApplyRelationshipDecisionInput
type UpsertSearchDocumentInput = knowledgepostgres.UpsertSearchDocumentInput
type SearchDocumentResult = knowledgepostgres.SearchDocumentResult
type FullTextSearchInput = knowledgepostgres.FullTextSearchInput
type ExactVectorSearchInput = knowledgepostgres.ExactVectorSearchInput
