package memoryservice

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/markhuangai/dense-mem/internal/assessor"
	"github.com/markhuangai/dense-mem/internal/domain"
	"github.com/markhuangai/dense-mem/internal/observability"
	"github.com/markhuangai/dense-mem/internal/repository"
	rememberapp "github.com/markhuangai/dense-mem/internal/service/remember"
)

func (s *submissionAssessmentPlacementWorkerService) persistPreparedAssessment(
	ctx context.Context,
	run repository.PlacementRun,
	request assessor.SemanticAssessmentRequest,
	response assessor.SemanticAssessmentResponse,
) (*repository.SubmissionAssessment, error) {
	if s == nil || s.assessments == nil || s.provider == nil {
		return nil, errors.New("synchronous assessment: persistence dependencies are required")
	}
	encoded, err := json.Marshal(response)
	if err != nil {
		return nil, err
	}
	canonicalJSON, err := assessor.CanonicalJSON(encoded)
	if err != nil {
		return nil, err
	}
	inputTokens := response.InputTokens
	if inputTokens <= 0 {
		inputTokens = request.InputTokens
	}
	persisted, _, err := s.assessments.PersistSubmissionAssessment(ctx, repository.PersistSubmissionAssessmentInput{
		TeamID: run.TeamID, OwnerProfileID: run.OwnerProfileID, IngestID: run.IngestID,
		PlacementRunID: run.PlacementRunID, RequestID: request.RequestID,
		AssessorContractVersion: domain.ContractVersion, Model: s.provider.ModelName(),
		Tokenizer: assessmentTokenizer(s.limits), ProviderTurns: response.ProviderTurns,
		InputTokens: inputTokens, OutputTokens: response.OutputTokens,
		CandidateContextTokens:    request.CandidateContextTokens,
		CandidateContextTruncated: request.CandidateContextTruncated,
		NormalizedResponse:        canonicalJSON, ResponseHash: semanticAssessmentHash(canonicalJSON),
		ValidatedAt: s.now().UTC(),
	})
	return persisted, err
}

// SynchronousAssessmentDependencies are the provider-facing dependencies for a
// request-owned Remember assessment. No durable ledger or assessment
// repository is needed until the provider has returned a valid response.
type SynchronousAssessmentDependencies struct {
	Catalog  SubmissionAssessmentCatalog
	Provider assessor.Provider
	Limits   assessor.SemanticAssessmentLimits
	Metrics  observability.DiscoverabilityMetrics
	Logger   observability.LogProvider
}

// SynchronousAssessmentInput is an in-memory snapshot of the exact request.
// The IDs are generated by the application before provider work and reused by
// the later durable commit.
type SynchronousAssessmentInput struct {
	Run       repository.PlacementRun
	Placement *repository.CreateIngestResult
}

// SynchronousAssessmentResult contains the validated whole response and its
// prepared request. The private plan is intentionally retained here so the
// existing deterministic commit-input builder remains the only policy path.
type SynchronousAssessmentResult struct {
	Response assessor.SemanticAssessmentResponse
	Request  assessor.SemanticAssessmentRequest
	Plan     submissionAssessmentPlan
}

// AssessSynchronousRemember performs catalog loading, one assessor
// conversation, and bounded complete-response repair without writing intake,
// assessment, or semantic rows.
func AssessSynchronousRemember(
	ctx context.Context,
	deps SynchronousAssessmentDependencies,
	input SynchronousAssessmentInput,
) (*SynchronousAssessmentResult, error) {
	assessmentCtx, cancel := context.WithTimeout(ctx, 160*time.Second)
	defer cancel()
	ctx = assessmentCtx
	if deps.Catalog == nil {
		return nil, errors.New("synchronous assessment: catalog is required")
	}
	if deps.Provider == nil {
		return nil, errors.New("synchronous assessment: provider is required")
	}
	if input.Placement == nil {
		return nil, errors.New("synchronous assessment: placement snapshot is required")
	}
	if strings.TrimSpace(input.Run.TeamID) == "" || strings.TrimSpace(input.Run.OwnerProfileID) == "" {
		return nil, errors.New("synchronous assessment: authenticated scope is required")
	}
	plan, err := buildSubmissionAssessmentPlan(input.Placement)
	if err != nil {
		return nil, err
	}
	contents := make([]string, 0, len(plan.Items))
	for _, item := range plan.Items {
		contents = append(contents, item.Fragment.Content)
	}
	if _, scanErr := scanSubmissionWithProviderProposal(contents, assessmentClientProposalWithoutTrustedContext(input.Placement.Proposal)); scanErr != nil {
		return nil, scanErr
	}
	worker := NewSubmissionAssessmentPlacementWorkerService(SubmissionAssessmentPlacementWorkerDependencies{
		Catalog: deps.Catalog, Provider: deps.Provider, Limits: deps.Limits,
		Metrics: deps.Metrics, Logger: deps.Logger,
		TeamID: input.Run.TeamID, OwnerProfileID: input.Run.OwnerProfileID,
		WorkerID: "remember-sync-prepared", Lease: 3 * time.Minute,
	})
	concrete := worker
	request, err := concrete.buildRequest(ctx, input.Run, plan, input.Placement.Proposal)
	if err != nil {
		return nil, normalizeSynchronousAssessmentPreflightError(err)
	}
	refresh := func(refreshCtx context.Context) (assessor.SemanticAssessmentRequest, error) {
		request, err := concrete.buildRequest(refreshCtx, input.Run, plan, input.Placement.Proposal)
		if err != nil {
			return assessor.SemanticAssessmentRequest{}, normalizeSynchronousAssessmentPreflightError(err)
		}
		return request, nil
	}
	providerCtx := observability.WithMetricIdentity(ctx, input.Run.TeamID, input.Run.OwnerProfileID)
	providerCtx = observability.WithAIOperation(providerCtx, observability.AIOperationPlacementAssessment, 1)
	response, _, finalRequest, err := concrete.assessRememberSession(providerCtx, request, refresh, 0)
	if err != nil {
		if errors.Is(err, context.DeadlineExceeded) {
			return nil, fmt.Errorf("%w: assessor phase exceeded 160 seconds", rememberapp.ErrRememberRequestTimeout)
		}
		if errors.Is(err, context.Canceled) {
			return nil, context.Canceled
		}
		if errors.Is(err, assessor.ErrVerifierMalformedResponse) {
			return nil, fmt.Errorf("%w: complete assessor response remained invalid", rememberapp.ErrRememberProviderResponseInvalid)
		}
		return nil, fmt.Errorf("%w: assessor provider request failed", rememberapp.ErrRememberProviderUnavailable)
	}
	return &SynchronousAssessmentResult{Response: response, Request: finalRequest, Plan: plan}, nil
}

func normalizeSynchronousAssessmentPreflightError(err error) error {
	if err == nil {
		return nil
	}
	stage, _ := semanticAssessmentPreflightFailure(err)
	switch stage {
	case "entity_catalog", "catalog_context", "assessment_input", "predicate_options_overflow":
		return fmt.Errorf("%w: %v", rememberapp.ErrRememberInputBudgetExceeded, err)
	default:
		return err
	}
}

// ProcessPreparedSynchronousRemember runs the existing owner-scoped commit
// engine with a response that was already assessed before durable staging.
func ProcessPreparedSynchronousRemember(
	ctx context.Context,
	deps SubmissionAssessmentPlacementWorkerDependencies,
	submissionID string,
	prepared *SynchronousAssessmentResult,
) (bool, error) {
	if prepared == nil {
		return false, errors.New("synchronous assessment: prepared result is required")
	}
	concrete := NewSubmissionAssessmentPlacementWorkerService(deps)
	concrete.prepared = prepared
	return concrete.ProcessSubmissionAssessmentPlacement(ctx, submissionID)
}
