package postgres

import (
	conflictcontract "github.com/markhuangai/dense-mem/internal/conflict/contract"
)

type ConflictRuntimeConfig = conflictcontract.ConflictRuntimeConfig

type ConflictReviewRunInput = conflictcontract.ConflictReviewRunInput

type ConflictReviewRunCompleteInput = conflictcontract.ConflictReviewRunCompleteInput

type ConflictReviewRunRecord = conflictcontract.ConflictReviewRunRecord

type ClaimRelationshipConflictCasesInput = conflictcontract.ClaimRelationshipConflictCasesInput

// ReleaseRelationshipConflictCaseClaimInput identifies the worker claim that
// should be returned to the conflict queue after retryable processing fails.
type ReleaseRelationshipConflictCaseClaimInput = conflictcontract.ReleaseRelationshipConflictCaseClaimInput

type ReviewRelationshipConflictCaseInput = conflictcontract.ReviewRelationshipConflictCaseInput

type ReviewRelationshipConflictCaseResult = conflictcontract.ReviewRelationshipConflictCaseResult

// RelationshipConflictResolutionInput identifies one selected resolution. The
// repository revalidates every field before it mutates durable state.
type RelationshipConflictResolutionInput = conflictcontract.RelationshipConflictResolutionInput

type RelationshipConflictResolutionDocument = conflictcontract.RelationshipConflictResolutionDocument

type RelationshipConflictResolutionFence = conflictcontract.RelationshipConflictResolutionFence

type RelationshipConflictResolutionPlan = conflictcontract.RelationshipConflictResolutionPlan

type RelationshipConflictResolutionEmbedding = conflictcontract.RelationshipConflictResolutionEmbedding

type CommitRelationshipConflictResolutionInput = conflictcontract.CommitRelationshipConflictResolutionInput

type RelationshipConflictCaseRecord = conflictcontract.RelationshipConflictCaseRecord
type RelationshipConflictPositionRecord = conflictcontract.RelationshipConflictPositionRecord
type RelationshipConflictSupporterRecord = conflictcontract.RelationshipConflictSupporterRecord

type ValidateRelationshipConflictContextInput = conflictcontract.ValidateRelationshipConflictContextInput
type ReserveOverdueConflictAssessmentInput = conflictcontract.ReserveOverdueConflictAssessmentInput
type OverdueConflictAssessmentReservation = conflictcontract.OverdueConflictAssessmentReservation
type OverdueConflictAssessmentDossier = conflictcontract.OverdueConflictAssessmentDossier
type OverdueConflictAssessmentPosition = conflictcontract.OverdueConflictAssessmentPosition
type OverdueConflictAssessmentEvidence = conflictcontract.OverdueConflictAssessmentEvidence
type CompleteOverdueConflictAssessmentInput = conflictcontract.CompleteOverdueConflictAssessmentInput
type CompleteOverdueConflictAssessmentResult = conflictcontract.CompleteOverdueConflictAssessmentResult
type ApplyOverdueConflictResolutionInput = conflictcontract.ApplyOverdueConflictResolutionInput
type ApplyOverdueConflictResolutionResult = conflictcontract.ApplyOverdueConflictResolutionResult
type ResumePendingOverdueConflictResolutionInput = conflictcontract.ResumePendingOverdueConflictResolutionInput
type ConflictDerivedEvidenceTarget = conflictcontract.ConflictDerivedEvidenceTarget
type ClaimConflictDerivedEvidenceTasksInput = conflictcontract.ClaimConflictDerivedEvidenceTasksInput
type StageConflictDerivedEvidenceResult = conflictcontract.StageConflictDerivedEvidenceResult
