package postgres

import knowledgecontract "github.com/markhuangai/dense-mem/internal/knowledge/contract"

type CreateEntityInput = knowledgecontract.CreateEntityInput
type AddEntityNameInput = knowledgecontract.AddEntityNameInput
type EntityRecord = knowledgecontract.EntityRecord
type SemanticReviewEntityCandidateInput = knowledgecontract.SemanticReviewEntityCandidateInput
type SemanticReviewEntityCandidate = knowledgecontract.SemanticReviewEntityCandidate
type SemanticAssessmentEntityMatch = knowledgecontract.SemanticAssessmentEntityMatch
type SemanticAssessmentEntityMatchInput = knowledgecontract.SemanticAssessmentEntityMatchInput
type SemanticAssessmentEntityMatchResult = knowledgecontract.SemanticAssessmentEntityMatchResult
type SemanticAssessmentKnownEntityInput = knowledgecontract.SemanticAssessmentKnownEntityInput
type SubmissionAssessmentKnownEvidence = knowledgecontract.SubmissionAssessmentKnownEvidence
type SubmissionAssessmentKnownEvidenceInput = knowledgecontract.SubmissionAssessmentKnownEvidenceInput
type SubmissionAssessmentKnownEvidenceResult = knowledgecontract.SubmissionAssessmentKnownEvidenceResult
type SemanticReviewPredicateCandidateInput = knowledgecontract.SemanticReviewPredicateCandidateInput
type SemanticReviewPredicateResolutionInput = knowledgecontract.SemanticReviewPredicateResolutionInput
type SemanticReviewPredicateResolution = knowledgecontract.SemanticReviewPredicateResolution
type SemanticReviewPredicateOptionsInput = knowledgecontract.SemanticReviewPredicateOptionsInput
type EnsureSemanticPredicateCandidateInput = knowledgecontract.EnsureSemanticPredicateCandidateInput
type SemanticReviewPredicateCandidate = knowledgecontract.SemanticReviewPredicateCandidate
type SemanticAssessmentPredicateOptionsInput = knowledgecontract.SemanticAssessmentPredicateOptionsInput
type SubmissionAssessmentEntityCatalogInput = knowledgecontract.SubmissionAssessmentEntityCatalogInput
type SubmissionAssessmentEntityCatalogTarget = knowledgecontract.SubmissionAssessmentEntityCatalogTarget
type SubmissionAssessmentEntityCatalogGroup = knowledgecontract.SubmissionAssessmentEntityCatalogGroup
type SubmissionAssessmentEntityCatalogResult = knowledgecontract.SubmissionAssessmentEntityCatalogResult
type UpsertValueInput = knowledgecontract.UpsertValueInput
type ValueRecord = knowledgecontract.ValueRecord
type EvidenceSupportInput = knowledgecontract.EvidenceSupportInput
type ApplyRelationshipDecisionInput = knowledgecontract.ApplyRelationshipDecisionInput
type RelationshipRecord = knowledgecontract.RelationshipRecord
type RelationshipDecisionResult = knowledgecontract.RelationshipDecisionResult
type RetractRelationshipInput = knowledgecontract.RetractRelationshipInput
type RelationshipTransitionResult = knowledgecontract.RelationshipTransitionResult
type RelationshipCorrectionEntityPatch = knowledgecontract.RelationshipCorrectionEntityPatch
type RelationshipCorrectionPredicatePatch = knowledgecontract.RelationshipCorrectionPredicatePatch
type RelationshipCorrectionPatch = knowledgecontract.RelationshipCorrectionPatch
type RelationshipCorrectionSupport = knowledgecontract.RelationshipCorrectionSupport
type RelationshipCorrectionSelection = knowledgecontract.RelationshipCorrectionSelection
type CorrectRelationshipInput = knowledgecontract.CorrectRelationshipInput
type RelationshipCorrectionCandidate = knowledgecontract.RelationshipCorrectionCandidate
type RelationshipCorrectionConfirmation = knowledgecontract.RelationshipCorrectionConfirmation
type RelationshipCorrectionResult = knowledgecontract.RelationshipCorrectionResult
type CorrectRelationshipResult = knowledgecontract.CorrectRelationshipResult
type RelationshipCorrectionEmbeddingPlan = knowledgecontract.RelationshipCorrectionEmbeddingPlan
type RelationshipCorrectionEmbeddingDocument = knowledgecontract.RelationshipCorrectionEmbeddingDocument
type RelationshipCorrectionEmbedding = knowledgecontract.RelationshipCorrectionEmbedding
type GetRelationshipCorrectionInput = knowledgecontract.GetRelationshipCorrectionInput
type RelationshipCorrectionStatus = knowledgecontract.RelationshipCorrectionStatus
type AppendCrossReferenceInput = knowledgecontract.AppendCrossReferenceInput
type ApplyRelationshipSupportDecisionInput = knowledgecontract.ApplyRelationshipSupportDecisionInput
type RelationshipSupportDecisionResult = knowledgecontract.RelationshipSupportDecisionResult
type SemanticEntityResolutionInput = knowledgecontract.SemanticEntityResolutionInput
type SemanticRelationshipDecisionInput = knowledgecontract.SemanticRelationshipDecisionInput
type SemanticPredicateCandidateInput = knowledgecontract.SemanticPredicateCandidateInput
type SemanticCorrectionTargetInput = knowledgecontract.SemanticCorrectionTargetInput
type SemanticValueInput = knowledgecontract.SemanticValueInput

type ActiveSearchContract = knowledgecontract.ActiveSearchContract
type FullTextSearchInput = knowledgecontract.FullTextSearchInput
type ExactVectorSearchInput = knowledgecontract.ExactVectorSearchInput
type SearchDocumentResult = knowledgecontract.SearchDocumentResult
type SearchDocumentForEmbedding = knowledgecontract.SearchDocumentForEmbedding
type InlineEmbeddingPlan = knowledgecontract.InlineEmbeddingPlan
type InlineEmbeddingResult = knowledgecontract.InlineEmbeddingResult
type UpsertSearchDocumentInput = knowledgecontract.UpsertSearchDocumentInput
type LoadSearchDocumentsForEmbeddingInput = knowledgecontract.LoadSearchDocumentsForEmbeddingInput
type LoadSearchDocumentsForSourcesInput = knowledgecontract.LoadSearchDocumentsForSourcesInput
type SearchDocumentEmbedding = knowledgecontract.SearchDocumentEmbedding
type CompleteSearchDocumentsWithEmbeddingsInput = knowledgecontract.CompleteSearchDocumentsWithEmbeddingsInput

type RememberCommitScope = knowledgecontract.RememberCommitScope
type SubmissionAssessment = knowledgecontract.SubmissionAssessment
type SubmissionAssessmentItemInput = knowledgecontract.SubmissionAssessmentItemInput
type SubmissionAssessmentEntityResolutionInput = knowledgecontract.SubmissionAssessmentEntityResolutionInput
type SubmissionAssessmentRelationshipObservationInput = knowledgecontract.SubmissionAssessmentRelationshipObservationInput
type EvidenceConflictPositionInput = knowledgecontract.EvidenceConflictPositionInput
type EvidenceConflictResultInput = knowledgecontract.EvidenceConflictResultInput
type SubmissionRelationshipSplitInput = knowledgecontract.SubmissionRelationshipSplitInput
type SubmissionRelationshipResult = knowledgecontract.SubmissionRelationshipResult
type SubmissionRelationshipResultInput = knowledgecontract.SubmissionRelationshipResultInput
type SubmissionPredicateRegistrationInput = knowledgecontract.SubmissionPredicateRegistrationInput
type CommitSubmissionAssessmentInput = knowledgecontract.CommitSubmissionAssessmentInput
type EvidenceSecurityResult = knowledgecontract.EvidenceSecurityResult
type SynchronousRememberCommitInput = knowledgecontract.SynchronousRememberCommitInput
type CommitSubmissionAssessmentResult = knowledgecontract.CommitSubmissionAssessmentResult
type SubmissionAssessmentSecurityQuarantineInput = knowledgecontract.SubmissionAssessmentSecurityQuarantineInput

type ValidateRelationshipConflictContextInput = knowledgecontract.ValidateRelationshipConflictContextInput
type CommitSemanticInput = knowledgecontract.CommitSemanticInput
type SemanticConflictContextInput = knowledgecontract.SemanticConflictContextInput

type ConflictRuntimeConfig = knowledgecontract.ConflictRuntimeConfig
type ConflictReviewRunInput = knowledgecontract.ConflictReviewRunInput
type ConflictReviewRunCompleteInput = knowledgecontract.ConflictReviewRunCompleteInput
type ConflictReviewRunRecord = knowledgecontract.ConflictReviewRunRecord
type ClaimRelationshipConflictCasesInput = knowledgecontract.ClaimRelationshipConflictCasesInput
type ReleaseRelationshipConflictCaseClaimInput = knowledgecontract.ReleaseRelationshipConflictCaseClaimInput
type ReviewRelationshipConflictCaseInput = knowledgecontract.ReviewRelationshipConflictCaseInput
type ReviewRelationshipConflictCaseResult = knowledgecontract.ReviewRelationshipConflictCaseResult
type RelationshipConflictResolutionInput = knowledgecontract.RelationshipConflictResolutionInput
type RelationshipConflictResolutionDocument = knowledgecontract.RelationshipConflictResolutionDocument
type RelationshipConflictResolutionFence = knowledgecontract.RelationshipConflictResolutionFence
type RelationshipConflictResolutionPlan = knowledgecontract.RelationshipConflictResolutionPlan
type RelationshipConflictResolutionEmbedding = knowledgecontract.RelationshipConflictResolutionEmbedding
type CommitRelationshipConflictResolutionInput = knowledgecontract.CommitRelationshipConflictResolutionInput
type RelationshipConflictCaseRecord = knowledgecontract.RelationshipConflictCaseRecord
type EvidenceConflictPositionRecord = knowledgecontract.EvidenceConflictPositionRecord
type EvidenceConflictEventRecord = knowledgecontract.EvidenceConflictEventRecord
type EvidenceConflictCaseRecord = knowledgecontract.EvidenceConflictCaseRecord
type EvidenceConflictListInput = knowledgecontract.EvidenceConflictListInput
type EvidenceConflictListResult = knowledgecontract.EvidenceConflictListResult
type EvidenceConflictCursor = knowledgecontract.EvidenceConflictCursor
type EvidenceConflictGetInput = knowledgecontract.EvidenceConflictGetInput
type EvidenceConflictEventCursor = knowledgecontract.EvidenceConflictEventCursor
type EvidenceConflictGetResult = knowledgecontract.EvidenceConflictGetResult
type EvidenceConflictResolutionInput = knowledgecontract.EvidenceConflictResolutionInput
type AdvanceSourceRevisionInput = knowledgecontract.AdvanceSourceRevisionInput
type SourceRevisionResult = knowledgecontract.SourceRevisionResult

type submissionSemanticCommitState struct {
	Status              string
	OutcomeID           string
	RelationshipResults []RelationshipDecisionResult
	SearchDocuments     []SearchDocumentResult
	EntityResolutionIDs []string
}
