#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_SOURCE_FILE="${DENSE_MEM_E2E_COMPOSE_SOURCE:-${ROOT_DIR}/docker-compose.yml}"
ROOT_ENV_SOURCE_FILE="${DENSE_MEM_E2E_ENV_SOURCE:-${ROOT_DIR}/.env}"
COMPOSE_FILE="$COMPOSE_SOURCE_FILE"
ROOT_ENV_FILE="$ROOT_ENV_SOURCE_FILE"
E2E_MODE="${DENSE_MEM_E2E_MODE:-standard}"
E2E_SCENARIO="${DENSE_MEM_E2E_SCENARIO:-full}"
E2E_MARKER="# dense-mem e2e generated by scripts/e2e-compose.sh"
COMPOSE_SOURCE_DIR=""
TEMP_DIR=""
E2E_FILES_PREPARED=0
E2E_ENV_FILE=""
E2E_COMPOSE_FILE=""
E2E_COMPOSE_OVERLAY_FILE=""
E2E_POSTGRES_COMPOSE_OVERLAY_FILE=""
E2E_PROMETHEUS_DIR=""
E2E_BIND_DIR=""
E2E_ENTRA_DIR=""
E2E_ENTRA_PORT=""
E2E_FILE_ID=""
E2E_SERVER_IMAGE=""
E2E_PLAYWRIGHT_CONTAINER=""

sanitize_project_name() {
  local raw="$1"
  local sanitized
  sanitized="$(printf '%s' "$raw" | tr '[:upper:]_' '[:lower:]-' | tr -cd 'a-z0-9-' | sed -e 's/--*/-/g' -e 's/^-//' -e 's/-$//')"
  if [[ -z "$sanitized" ]]; then
    sanitized="densemem-e2e"
  fi
  printf '%s' "$sanitized"
}

pick_ports() {
  local count="$1"
  node - "$count" <<'NODE'
const net = require("node:net");
const count = Number(process.argv[2]);
const servers = [];

function listen() {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      servers.push(server);
      resolve(server.address().port);
    });
  });
}

(async () => {
  const ports = [];
  for (let i = 0; i < count; i += 1) {
    ports.push(await listen());
  }
  console.log(ports.join(" "));
  for (const server of servers) {
    server.close();
  }
})().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
NODE
}

json_field() {
  local field="$1"
  node -e '
let input = "";
process.stdin.on("data", chunk => input += chunk);
process.stdin.on("end", () => {
  const value = process.argv[1]
    .split(".")
    .reduce((current, key) => current?.[key], JSON.parse(input));
  if (value === undefined || value === null || value === "") {
    process.exit(1);
  }
  process.stdout.write(String(value));
});
' "$field"
}

env_file_value() {
  local field="$1"
  node - "$ROOT_ENV_FILE" "$field" <<'NODE'
const fs = require("node:fs");
const path = process.argv[2];
const target = process.argv[3];

function decodeValue(raw) {
  const value = raw.trim();
  if (value.startsWith('"') || value.startsWith("'")) {
    const quote = value[0];
    const closing = closingQuoteIndex(value, quote);
    if (closing > 0) {
      const inner = value.slice(1, closing);
      if (quote === "'") {
        return inner;
      }
      return inner
        .replace(/\\n/g, "\n")
        .replace(/\\r/g, "\r")
        .replace(/\\t/g, "\t")
        .replace(/\\"/g, '"')
        .replace(/\\\\/g, "\\");
    }
  }
  return stripInlineComment(value).trim();
}

function closingQuoteIndex(value, quote) {
  for (let index = 1; index < value.length; index += 1) {
    if (quote === '"' && value[index] === "\\" && index + 1 < value.length) {
      index += 1;
      continue;
    }
    if (value[index] === quote) {
      return index;
    }
  }
  return -1;
}

function stripInlineComment(value) {
  for (let index = 0; index < value.length; index += 1) {
    if (value[index] === "#" && (index === 0 || /\s/.test(value[index - 1]))) {
      return value.slice(0, index);
    }
  }
  return value;
}

let resolved;
for (const line of fs.readFileSync(path, "utf8").split(/\r?\n/)) {
  const match = line.match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
  if (!match || match[1] !== target) {
    continue;
  }
  resolved = decodeValue(match[2]);
}
if (resolved !== undefined) {
  process.stdout.write(resolved);
} else {
  process.exit(1);
}
NODE
}

require_env_value() {
  local field="$1"
  local value=""
  if ! value="$(env_file_value "$field")" || [[ -z "$value" ]]; then
    echo "Missing required ${field} in ${ROOT_ENV_FILE}." >&2
    return 1
  fi
  printf '%s' "$value"
}

require_env_true() {
  local field="$1"
  local value=""
  value="$(require_env_value "$field")"
  case "$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')" in
    true|1|yes|y|on)
      return 0
      ;;
  esac
  echo "${field} must be true in ${ROOT_ENV_FILE} for compose e2e." >&2
  return 1
}

wait_for_url() {
  local label="$1"
  local url="$2"
  local header="${3:-}"
  for _ in $(seq 1 90); do
    if [[ -n "$header" ]]; then
      if curl -fsS -H "$header" "$url" >/dev/null 2>&1; then
        return 0
      fi
    elif curl -fsS "$url" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "Timed out waiting for ${label} at ${url}" >&2
  return 1
}

wait_for_entra_mock() {
  for _ in $(seq 1 90); do
    if curl --cacert "${E2E_ENTRA_DIR}/ca.pem" -fsS "https://localhost:${E2E_ENTRA_PORT}/.well-known/openid-configuration" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "Timed out waiting for the local Entra OIDC mock." >&2
  return 1
}

compose() {
  local compose_args=(-p "$COMPOSE_PROJECT_NAME" -f "$COMPOSE_FILE")
  if [[ -n "$E2E_POSTGRES_COMPOSE_OVERLAY_FILE" ]]; then
    compose_args+=(-f "$E2E_POSTGRES_COMPOSE_OVERLAY_FILE")
  fi
  if [[ -n "$E2E_COMPOSE_OVERLAY_FILE" ]]; then
    compose_args+=(-f "$E2E_COMPOSE_OVERLAY_FILE")
  fi
  docker compose "${compose_args[@]}" "$@"
}

is_generated_marker_file() {
  local path="$1"
  local first_line=""
  if [[ ! -f "$path" ]]; then
    return 1
  fi
  IFS= read -r first_line < "$path" || true
  [[ "$first_line" == "$E2E_MARKER" ]]
}

prepare_e2e_prometheus_files() {
  if [[ -e "$E2E_PROMETHEUS_DIR" ]]; then
    echo "Refusing to replace existing E2E Prometheus directory ${E2E_PROMETHEUS_DIR}." >&2
    return 1
  fi
  mkdir "$E2E_PROMETHEUS_DIR"
  chmod 755 "$E2E_PROMETHEUS_DIR"
  E2E_FILES_PREPARED=1

  cat > "${E2E_PROMETHEUS_DIR}/prometheus.yml" <<EOF
${E2E_MARKER}
global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: dense-mem
    metrics_path: /metrics
    authorization:
      credentials_file: /run/secrets/telemetry-scrape-token
    static_configs:
      - targets:
          - server:8090
EOF

  printf '%s\n' "$TELEMETRY_SCRAPE_TOKEN" > "${E2E_PROMETHEUS_DIR}/telemetry-scrape-token"
  chmod 644 "${E2E_PROMETHEUS_DIR}/prometheus.yml" "${E2E_PROMETHEUS_DIR}/telemetry-scrape-token"
}

prepare_e2e_environment() {
  E2E_ENV_FILE="${ROOT_DIR}/.env.e2e-${E2E_FILE_ID}"
  printf '%s\n' "$E2E_MARKER" > "$E2E_ENV_FILE"
  if [[ "$E2E_MODE" == "entra_scim" ]]; then
    printf '%s\n' \
      "LOG_LEVEL=warn" \
      "CONTROL_PORTAL_TOKEN=dense-mem-e2e-control-token" \
      "CONTROL_HTTP_ADDR=:8090" \
      "HTTP_ADDR=:8080" \
      "POSTGRES_USER=densemem" \
      "POSTGRES_PASSWORD=dense-mem-e2e-postgres-password" \
      "POSTGRES_DB=densemem" \
      "POSTGRES_HOST=postgres" \
      "POSTGRES_PORT=5432" \
      "POSTGRES_SSLMODE=disable" \
      "REDIS_ADDR=redis:6379" \
      "TELEMETRY_ENABLED=true" \
      "TELEMETRY_SCRAPE_TOKEN=dense-mem-e2e-scrape-token" \
      "AI_API_URL=http://127.0.0.1:65535/v1" \
      "AI_API_KEY=dense-mem-e2e-ai-key" \
      "AI_API_EMBEDDING_MODEL=dense-mem-e2e-embedding" \
      "AI_API_EMBEDDING_DIMENSIONS=1536" \
      "AI_VERIFIER_MODEL=dense-mem-e2e-verifier" \
      "EMBEDDING_WORKER_COUNT=1" \
      "MEMORY_PLACEMENT_WORKER_COUNT=1" >> "$E2E_ENV_FILE"
  else
    if [[ ! -f "$ROOT_ENV_SOURCE_FILE" ]]; then
      echo "Missing environment source at ${ROOT_ENV_SOURCE_FILE}; compose e2e uses the supplied local environment file." >&2
      return 1
    fi
    awk '
      /^[[:space:]]*(export[[:space:]]+)?NEO4J_[A-Za-z0-9_]*[[:space:]]*=/ { next }
      { print }
    ' "$ROOT_ENV_SOURCE_FILE" >> "$E2E_ENV_FILE"
  fi
  printf '%s\n' \
    "CONFLICT_REVIEW_START_TIME_LOCAL=00:00" \
    "CONFLICT_REVIEW_JITTER_SECONDS=0" >> "$E2E_ENV_FILE"
  ROOT_ENV_FILE="$E2E_ENV_FILE"
}

prepare_e2e_compose_files() {
  if [[ ! -f "$COMPOSE_SOURCE_FILE" ]]; then
    echo "Missing supported compose source at ${COMPOSE_SOURCE_FILE}." >&2
    return 1
  fi
  E2E_COMPOSE_FILE="${ROOT_DIR}/docker-compose.e2e-${E2E_FILE_ID}.yml"
  node - "$COMPOSE_SOURCE_FILE" "$E2E_COMPOSE_FILE" "$E2E_ENV_FILE" "$E2E_PROMETHEUS_DIR" "$ROOT_DIR" "$E2E_SERVER_IMAGE" "$E2E_MARKER" <<'NODE'
const fs = require("node:fs");

const [sourcePath, destinationPath, envFile, prometheusDir, worktreeRoot, serverImage, marker] = process.argv.slice(2);
let compose = fs.readFileSync(sourcePath, "utf8");

function replaceRequired(pattern, replacement, label, expectedCount) {
  let count = 0;
  compose = compose.replace(pattern, (...args) => {
    count += 1;
    return typeof replacement === "function" ? replacement(...args) : replacement;
  });
  if ((expectedCount === undefined && count === 0) || (expectedCount !== undefined && count !== expectedCount)) {
    const expected = expectedCount === undefined ? "at least one" : expectedCount;
    throw new Error(`expected ${expected} ${label} replacement(s), found ${count}`);
  }
}

replaceRequired(/^(\s*-\s*)\.env\s*$/gm, (_, prefix) => `${prefix}${envFile}`, "env_file");
replaceRequired(/^(\s*context:\s*)\.\s*$/gm, (_, prefix) => `${prefix}${worktreeRoot}`, "build context", 1);
replaceRequired(/^(\s*image:\s*)ghcr\.io\/z-m-huang\/dense-mem:latest\s*$/gm, (_, prefix) => `${prefix}${serverImage}`, "server image", 1);
replaceRequired(
  /^(\s*)-\s+\.\/?prometheus\.yml:\/etc\/prometheus\/prometheus\.yml:ro\s*$/m,
  (_, indent) => `${indent}- ${prometheusDir}/prometheus.yml:/etc/prometheus/prometheus.yml:ro`,
  "Prometheus config mount",
);
replaceRequired(
  /^(\s*)(?:file:\s*\.\/?telemetry-scrape-token|environment:\s*TELEMETRY_SCRAPE_TOKEN)\s*$/m,
  (_, indent) => `${indent}file: ${prometheusDir}/telemetry-scrape-token`,
  "telemetry secret source",
);
replaceRequired(
  /(^  prometheus:\r?\n[\s\S]*?)^    secrets:\r?\n      - telemetry-scrape-token\r?\n/m,
  (_, prometheusBlock) => `${prometheusBlock}    secrets:\n      - telemetry-scrape-token\n`,
  "Prometheus secret block",
);

fs.writeFileSync(destinationPath, `${marker}\n${compose}`);
NODE
  if ! grep -F -- "$E2E_ENV_FILE" "$E2E_COMPOSE_FILE" >/dev/null || ! grep -F -- "${E2E_PROMETHEUS_DIR}/prometheus.yml:/etc/prometheus/prometheus.yml:ro" "$E2E_COMPOSE_FILE" >/dev/null || ! grep -F -- "${E2E_PROMETHEUS_DIR}/telemetry-scrape-token" "$E2E_COMPOSE_FILE" >/dev/null || ! grep -F -- "context: ${ROOT_DIR}" "$E2E_COMPOSE_FILE" >/dev/null || ! grep -F -- "$E2E_SERVER_IMAGE" "$E2E_COMPOSE_FILE" >/dev/null; then
    echo "Generated compose file did not contain the expected E2E substitutions." >&2
    return 1
  fi
  COMPOSE_FILE="$E2E_COMPOSE_FILE"
}

prepare_postgres_e2e_overlay() {
  E2E_POSTGRES_COMPOSE_OVERLAY_FILE="${ROOT_DIR}/docker-compose.postgres-e2e-${E2E_FILE_ID}.yml"
  node - "$E2E_POSTGRES_COMPOSE_OVERLAY_FILE" "$E2E_MARKER" <<'NODE'
const fs = require("node:fs");

const [destination, marker] = process.argv.slice(2);
const contents = [
  marker,
  "services:",
  "  postgres:",
  "    environment:",
  "      POSTGRES_USER: densemem_e2e_bootstrap",
  "      POSTGRES_PASSWORD: dense-mem-e2e-bootstrap-password",
  "    healthcheck:",
  '      test: ["CMD-SHELL", "pg_isready -U densemem_e2e_bootstrap -d \\"$${POSTGRES_DB}\\""]',
  "",
].join("\n");
fs.writeFileSync(destination, contents);
NODE
}

compose_server_environment_value() {
  local field="$1"
  compose config --format json | json_field "services.server.environment.${field}"
}

wait_for_postgres_service() {
  for _ in $(seq 1 90); do
    if compose exec -T postgres sh -ec 'pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"' >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "Timed out waiting for the E2E PostgreSQL service." >&2
  return 1
}

provision_postgres_runtime_role() {
  local runtime_user
  local runtime_password
  local runtime_database
  local role_state
  runtime_user="$(compose_server_environment_value POSTGRES_USER)"
  runtime_password="$(compose_server_environment_value POSTGRES_PASSWORD)"
  runtime_database="$(compose_server_environment_value POSTGRES_DB)"

  if [[ "$runtime_user" == "densemem_e2e_bootstrap" || "$runtime_user" == "densemem_e2e_database_owner" ]]; then
    echo "POSTGRES_USER conflicts with an E2E provisioning role: ${runtime_user}" >&2
    return 1
  fi

  compose exec -T \
    -e "DENSE_MEM_RUNTIME_POSTGRES_USER=$runtime_user" \
    -e "DENSE_MEM_RUNTIME_POSTGRES_PASSWORD=$runtime_password" \
    -e "DENSE_MEM_RUNTIME_POSTGRES_DB=$runtime_database" \
    postgres sh -ec \
    'psql -v ON_ERROR_STOP=1 \
      -U "$POSTGRES_USER" \
      -d "$POSTGRES_DB" \
      -v runtime_user="$DENSE_MEM_RUNTIME_POSTGRES_USER" \
      -v runtime_password="$DENSE_MEM_RUNTIME_POSTGRES_PASSWORD" \
      -v runtime_database="$DENSE_MEM_RUNTIME_POSTGRES_DB"' <<'SQL'
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE ROLE :"runtime_user"
  LOGIN PASSWORD :'runtime_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE densemem_e2e_database_owner
  NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;

ALTER DATABASE :"runtime_database" OWNER TO densemem_e2e_database_owner;
GRANT CONNECT, CREATE, TEMPORARY ON DATABASE :"runtime_database" TO :"runtime_user";
GRANT USAGE, CREATE ON SCHEMA public TO :"runtime_user";
SQL

  role_state="$(
    compose exec -T \
      -e "PGPASSWORD=$runtime_password" \
      postgres psql -X -v ON_ERROR_STOP=1 -At -F '|' \
      -h 127.0.0.1 -U "$runtime_user" -d "$runtime_database" \
      -c "
        SELECT
          role.rolsuper,
          role.rolcreatedb,
          role.rolcreaterole,
          role.rolreplication,
          role.rolbypassrls,
          pg_get_userbyid(database.datdba) = CURRENT_USER,
          has_database_privilege(CURRENT_USER, current_database(), 'CREATE'),
          has_schema_privilege(CURRENT_USER, 'public', 'CREATE')
        FROM pg_roles AS role
        JOIN pg_database AS database ON database.datname = current_database()
        WHERE role.rolname = CURRENT_USER
      "
  )"
  if [[ "$role_state" != "f|f|f|f|f|f|t|t" ]]; then
    echo "Unexpected E2E PostgreSQL runtime role state: ${role_state}" >&2
    return 1
  fi
}

verify_postgres_runtime_migration_state() {
  local runtime_user
  local runtime_password
  local runtime_database
  local migration_state
  runtime_user="$(compose_server_environment_value POSTGRES_USER)"
  runtime_password="$(compose_server_environment_value POSTGRES_PASSWORD)"
  runtime_database="$(compose_server_environment_value POSTGRES_DB)"

  migration_state="$(
    compose exec -T \
      -e "PGPASSWORD=$runtime_password" \
      postgres psql -X -v ON_ERROR_STOP=1 -At -F '|' \
      -h 127.0.0.1 -U "$runtime_user" -d "$runtime_database" \
      -c "
        SELECT
          EXISTS (
            SELECT 1 FROM goose_db_version
            WHERE version_id = 2026080603 AND is_applied
          ),
          NOT EXISTS (
            SELECT 1 FROM pg_roles
            WHERE rolname = 'dense_mem_portal_session_system'
          ),
          NOT EXISTS (
            SELECT 1
            FROM pg_proc AS procedure
            JOIN pg_namespace AS namespace ON namespace.oid = procedure.pronamespace
            WHERE namespace.nspname = 'public'
              AND procedure.proname LIKE 'dense_mem_portal_session_%'
          ),
          table_state.relrowsecurity,
          table_state.relforcerowsecurity,
          pg_get_userbyid(table_state.relowner) = CURRENT_USER,
          policy.polcmd = '*',
          policy.polroles = ARRAY[0::oid],
          pg_get_expr(policy.polqual, policy.polrelid) LIKE '%current_setting%'
            AND pg_get_expr(policy.polqual, policy.polrelid) LIKE '%app.tx_mode%'
            AND pg_get_expr(policy.polqual, policy.polrelid) LIKE '%system%',
          pg_get_expr(policy.polwithcheck, policy.polrelid) LIKE '%current_setting%'
            AND pg_get_expr(policy.polwithcheck, policy.polrelid) LIKE '%app.tx_mode%'
            AND pg_get_expr(policy.polwithcheck, policy.polrelid) LIKE '%system%',
          NOT EXISTS (
            SELECT 1
            FROM pg_class AS relation
            JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
            WHERE namespace.nspname = 'public'
              AND relation.relkind IN ('r', 'p', 'S', 'v', 'm')
              AND pg_get_userbyid(relation.relowner) <> CURRENT_USER
          )
        FROM pg_class AS table_state
        JOIN pg_policy AS policy ON policy.polrelid = table_state.oid
        WHERE table_state.oid = to_regclass('public.user_portal_sessions')
          AND policy.polname = 'user_portal_sessions_system_access'
      "
  )"
  if [[ "$migration_state" != "t|t|t|t|t|t|t|t|t|t|t" ]]; then
    echo "Unexpected E2E PostgreSQL migration state: ${migration_state}" >&2
    return 1
  fi
}

prepare_entra_mock_files() {
  if [[ "$E2E_MODE" != "entra_scim" ]]; then
    return
  fi
  if [[ -e "$E2E_ENTRA_DIR" ]]; then
    echo "Refusing to replace existing Entra mock directory ${E2E_ENTRA_DIR}." >&2
    return 1
  fi
  mkdir "$E2E_ENTRA_DIR"
  printf '%s\n' "$E2E_MARKER" > "${E2E_ENTRA_DIR}/.dense-mem-e2e-marker"
  openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout "${E2E_ENTRA_DIR}/server.key" \
    -out "${E2E_ENTRA_DIR}/ca.pem" \
    -days 1 \
    -subj "/CN=entra-mock" \
    -addext "subjectAltName=DNS:entra-mock,DNS:localhost" >/dev/null 2>&1
  chmod 600 "${E2E_ENTRA_DIR}/server.key"
  chmod 644 "${E2E_ENTRA_DIR}/ca.pem"
  E2E_COMPOSE_OVERLAY_FILE="${ROOT_DIR}/docker-compose.entra-e2e-${E2E_FILE_ID}.yml"
  node - "$E2E_COMPOSE_OVERLAY_FILE" "$ROOT_DIR" "$E2E_ENTRA_DIR" "$E2E_ENTRA_PORT" "$E2E_MARKER" <<'NODE'
const fs = require("node:fs");

const [destination, rootDir, entraDir, entraPort, marker] = process.argv.slice(2);
const quote = (value) => JSON.stringify(value);
const mount = (source, target) => quote(`${source}:${target}:ro`);
const mockScript = `${entraDir}/entra-mock.mjs`;
const caFile = `${entraDir}/ca.pem`;
fs.copyFileSync(`${rootDir}/web/tests-compose/entra-mock.mjs`, mockScript);
const contents = `${marker}
services:
  server:
    environment:
      SSL_CERT_FILE: /e2e/entra-ca.pem
    volumes:
      - ${mount(caFile, "/e2e/entra-ca.pem")}
  entra-mock:
    image: node:22-alpine
    working_dir: /e2e
    command: ["node", "/e2e/entra-mock.mjs"]
    environment:
      DENSE_MEM_ENTRA_CERT: /e2e/tls/ca.pem
      DENSE_MEM_ENTRA_KEY: /e2e/tls/server.key
      DENSE_MEM_ENTRA_ISSUER: https://entra-mock:9443
    volumes:
      - ${mount(mockScript, "/e2e/entra-mock.mjs")}
      - ${mount(entraDir, "/e2e/tls")}
    ports:
      - "127.0.0.1:${entraPort}:9443"
`;
fs.writeFileSync(destination, contents);
NODE
}

restore_root_files() {
  if [[ "$E2E_FILES_PREPARED" != "1" || ! -d "$E2E_PROMETHEUS_DIR" ]]; then
    return
  fi
  if is_generated_marker_file "${E2E_PROMETHEUS_DIR}/prometheus.yml"; then
    rm -r "$E2E_PROMETHEUS_DIR"
  fi
}

remove_e2e_images() {
  if [[ -n "$E2E_SERVER_IMAGE" ]] && docker image inspect "$E2E_SERVER_IMAGE" >/dev/null 2>&1; then
    if ! docker image rm "$E2E_SERVER_IMAGE" >/dev/null; then
      echo "Failed to remove e2e image ${E2E_SERVER_IMAGE}." >&2
    fi
  fi
}

create_control_team() {
  local name="$1"
  local description="$2"
  local payload
  local response
  payload="$(node -e 'process.stdout.write(JSON.stringify({name: process.argv[1], description: process.argv[2]}))' "$name" "$description")"
  response="$(curl -fsS \
    -H "Authorization: Bearer ${CONTROL_TOKEN}" \
    -H "Content-Type: application/json" \
    --data "$payload" \
    "${CONTROL_URL}/control/api/teams")"
  CREATED_TEAM_ID="$(printf '%s' "$response" | json_field data.id)"
}

create_control_profile() {
  local team_id="$1"
  local name="$2"
  local payload
  local response
  payload="$(node -e 'process.stdout.write(JSON.stringify({name: process.argv[1], rate_limit: 300}))' "$name")"
  response="$(curl -fsS \
    -H "Authorization: Bearer ${CONTROL_TOKEN}" \
    -H "Content-Type: application/json" \
    --data "$payload" \
    "${CONTROL_URL}/control/api/teams/${team_id}/profiles")"
  CREATED_API_KEY="$(printf '%s' "$response" | json_field data.api_key)"
}

remove_e2e_playwright_container() {
  if [[ -n "$E2E_PLAYWRIGHT_CONTAINER" ]] && docker container inspect "$E2E_PLAYWRIGHT_CONTAINER" >/dev/null 2>&1; then
    if ! docker rm -f "$E2E_PLAYWRIGHT_CONTAINER" >/dev/null; then
      echo "Failed to remove e2e Playwright container ${E2E_PLAYWRIGHT_CONTAINER}." >&2
    fi
  fi
}

run_compose_playwright_tests() {
  local image
  local test_args=()
  if [[ "${1:-}" == "portal" ]]; then
    test_args=(
      "tests-compose/compose-portal.spec.ts"
      -g
      "remembered API-key login uses a seven-day server session"
    )
  fi
  image="${DENSE_MEM_E2E_PLAYWRIGHT_IMAGE:-mcr.microsoft.com/playwright:v1.61.0-noble}"
  E2E_PLAYWRIGHT_CONTAINER="densemem-e2e-${E2E_FILE_ID}-playwright"
  if docker container inspect "$E2E_PLAYWRIGHT_CONTAINER" >/dev/null 2>&1; then
    echo "Container ${E2E_PLAYWRIGHT_CONTAINER} already exists; choose another DENSE_MEM_E2E_RUN_ID." >&2
    return 1
  fi

  docker create --name "$E2E_PLAYWRIGHT_CONTAINER" --network host "$image" sleep infinity >/dev/null
  docker start "$E2E_PLAYWRIGHT_CONTAINER" >/dev/null
  docker exec "$E2E_PLAYWRIGHT_CONTAINER" mkdir -p /tmp/web
  tar \
    --exclude='./node_modules' \
    --exclude='./node_modules/*' \
    --exclude='./dist' \
    --exclude='./dist/*' \
    -C "$ROOT_DIR/web" \
    -cf - . | docker cp - "${E2E_PLAYWRIGHT_CONTAINER}:/tmp/web"
  docker exec \
    -e "PLAYWRIGHT_BROWSERS_PATH=/ms-playwright" \
    -e "DENSE_MEM_CONTROL_URL=$CONTROL_URL" \
    -e "DENSE_MEM_USER_URL=$USER_URL" \
    -e "DENSE_MEM_CONTROL_TOKEN=$CONTROL_TOKEN" \
    -e "DENSE_MEM_E2E_TEAM_ID=$team_id" \
    -e "DENSE_MEM_E2E_TEAM_NAME=E2E Team" \
    -e "DENSE_MEM_E2E_API_KEY=$api_key" \
    -e "DENSE_MEM_E2E_DREAM_STATEMENT=$dream_statement" \
    -e "DENSE_MEM_PROMETHEUS_URL=$PROMETHEUS_URL" \
    "$E2E_PLAYWRIGHT_CONTAINER" \
    sh -ec 'cd /tmp/web && npm ci && ./node_modules/.bin/playwright test --config playwright.compose.config.ts "$@"' \
    sh "${test_args[@]}"
  remove_e2e_playwright_container
}

cleanup() {
  local status=$?
  set +e
  remove_e2e_playwright_container
  if [[ "$E2E_FILES_PREPARED" == "1" && "${DENSE_MEM_E2E_KEEP_COMPOSE:-0}" != "1" ]]; then
    if ! compose down -v --remove-orphans >/dev/null; then
      echo "Failed to clean up e2e compose project ${COMPOSE_PROJECT_NAME}." >&2
    fi
    remove_e2e_images
    sleep 1
  elif [[ "${DENSE_MEM_E2E_KEEP_COMPOSE:-0}" == "1" ]]; then
    echo "Keeping e2e compose project ${COMPOSE_PROJECT_NAME}."
  fi
  restore_root_files
  if [[ -n "$E2E_ENV_FILE" && -f "$E2E_ENV_FILE" ]] && is_generated_marker_file "$E2E_ENV_FILE"; then
    rm -- "$E2E_ENV_FILE"
  fi
  if [[ -n "$E2E_COMPOSE_FILE" && -f "$E2E_COMPOSE_FILE" ]] && is_generated_marker_file "$E2E_COMPOSE_FILE"; then
    rm -- "$E2E_COMPOSE_FILE"
  fi
  if [[ -n "$E2E_COMPOSE_OVERLAY_FILE" && -f "$E2E_COMPOSE_OVERLAY_FILE" ]] && is_generated_marker_file "$E2E_COMPOSE_OVERLAY_FILE"; then
    rm -- "$E2E_COMPOSE_OVERLAY_FILE"
  fi
  if [[ -n "$E2E_POSTGRES_COMPOSE_OVERLAY_FILE" && -f "$E2E_POSTGRES_COMPOSE_OVERLAY_FILE" ]] && is_generated_marker_file "$E2E_POSTGRES_COMPOSE_OVERLAY_FILE"; then
    rm -- "$E2E_POSTGRES_COMPOSE_OVERLAY_FILE"
  fi
  if [[ -n "$E2E_ENTRA_DIR" && -f "${E2E_ENTRA_DIR}/.dense-mem-e2e-marker" ]] && is_generated_marker_file "${E2E_ENTRA_DIR}/.dense-mem-e2e-marker"; then
    rm -r "$E2E_ENTRA_DIR"
  fi
  if [[ -n "$TEMP_DIR" && -d "$TEMP_DIR" ]]; then
    rm -r "$TEMP_DIR"
  fi
  exit "$status"
}

if [[ ! -f "$COMPOSE_SOURCE_FILE" ]]; then
  echo "Missing compose source at ${COMPOSE_SOURCE_FILE}." >&2
  exit 1
fi
COMPOSE_SOURCE_DIR="$(cd "$(dirname "$COMPOSE_SOURCE_FILE")" && pwd)"

if [[ "$E2E_MODE" != "standard" && "$E2E_MODE" != "entra_scim" ]]; then
  echo "DENSE_MEM_E2E_MODE must be standard or entra_scim." >&2
  exit 1
fi

if [[ "$E2E_SCENARIO" != "full" && "$E2E_SCENARIO" != "portal" && "$E2E_SCENARIO" != "mcp_boundaries" && "$E2E_SCENARIO" != "submission_status" && "$E2E_SCENARIO" != "security_intake" && "$E2E_SCENARIO" != "submission_assessment" && "$E2E_SCENARIO" != "semantic_holds" && "$E2E_SCENARIO" != "all" ]]; then
  echo "DENSE_MEM_E2E_SCENARIO must be full, portal, mcp_boundaries, submission_status, security_intake, submission_assessment, semantic_holds, or all." >&2
  exit 1
fi

if [[ "$E2E_MODE" == "entra_scim" && "$E2E_SCENARIO" != "full" ]]; then
  echo "DENSE_MEM_E2E_MODE=entra_scim supports only the full scenario." >&2
  exit 1
fi

if [[ "$E2E_SCENARIO" == "all" ]]; then
  if [[ "$E2E_MODE" != "standard" ]]; then
    echo "DENSE_MEM_E2E_SCENARIO=all requires DENSE_MEM_E2E_MODE=standard." >&2
    exit 1
  fi
  for scenario in submission_status security_intake submission_assessment semantic_holds full; do
    echo "Running compose e2e scenario ${scenario} as part of all."
    DENSE_MEM_E2E_SCENARIO="$scenario" \
    DENSE_MEM_E2E_RUN_ID="${DENSE_MEM_E2E_RUN_ID:-all}-$(printf '%s' "$scenario" | tr '[:upper:]' '[:lower:]')" \
    DENSE_MEM_E2E_SKIP_PRECHECKS="${DENSE_MEM_E2E_SKIP_PRECHECKS:-1}" \
    "$0"
  done
  exit 0
fi

if [[ "$E2E_MODE" == "standard" && ! -f "$ROOT_ENV_SOURCE_FILE" ]]; then
  echo "Missing environment source at ${ROOT_ENV_SOURCE_FILE}; compose e2e uses the supplied local environment file." >&2
  exit 1
fi

E2E_RUN_ID="${DENSE_MEM_E2E_RUN_ID:-$(date -u +%Y%m%d%H%M%S)-$$}"
E2E_FILE_ID="$(sanitize_project_name "$E2E_RUN_ID")"
COMPOSE_PROJECT_NAME="$(sanitize_project_name "${DENSE_MEM_E2E_PROJECT_NAME:-densemem-e2e-${E2E_RUN_ID}}")"
E2E_SERVER_IMAGE="densemem-e2e-${E2E_FILE_ID}-server:latest"
# Docker Desktop may need a bind-mountable directory outside a /tmp worktree.
E2E_BIND_DIR="${DENSE_MEM_E2E_BIND_DIR:-${COMPOSE_SOURCE_DIR}}"
if [[ ! -d "$E2E_BIND_DIR" || ! -w "$E2E_BIND_DIR" ]]; then
  echo "DENSE_MEM_E2E_BIND_DIR must be an existing writable directory: ${E2E_BIND_DIR}." >&2
  exit 1
fi
E2E_PROMETHEUS_DIR="${E2E_BIND_DIR}/densemem-e2e-prometheus-${E2E_FILE_ID}"
E2E_ENTRA_DIR="${E2E_BIND_DIR}/densemem-e2e-entra-${E2E_FILE_ID}"
read -r \
  generated_api_port \
  generated_control_port \
  generated_prometheus_port \
  generated_postgres_port \
  generated_neo4j_http_port \
  generated_neo4j_bolt_port \
  generated_redis_port \
  generated_entra_port < <(pick_ports 8)
DENSE_MEM_PORT="${DENSE_MEM_E2E_API_PORT:-$generated_api_port}"
CONTROL_PORTAL_PORT="${DENSE_MEM_E2E_CONTROL_PORT:-$generated_control_port}"
PROMETHEUS_PORT="${DENSE_MEM_E2E_PROMETHEUS_PORT:-$generated_prometheus_port}"
POSTGRES_HOST_PORT="${DENSE_MEM_E2E_POSTGRES_PORT:-$generated_postgres_port}"
NEO4J_HTTP_HOST_PORT="${DENSE_MEM_E2E_NEO4J_HTTP_PORT:-$generated_neo4j_http_port}"
NEO4J_BOLT_HOST_PORT="${DENSE_MEM_E2E_NEO4J_BOLT_PORT:-$generated_neo4j_bolt_port}"
REDIS_PORT="${DENSE_MEM_E2E_REDIS_PORT:-$generated_redis_port}"
E2E_ENTRA_PORT="${DENSE_MEM_E2E_ENTRA_PORT:-$generated_entra_port}"
PROMETHEUS_CONTAINER_NAME="${DENSE_MEM_E2E_PROMETHEUS_CONTAINER_NAME:-${COMPOSE_PROJECT_NAME}-prometheus}"
CONTROL_URL="${DENSE_MEM_CONTROL_URL:-http://127.0.0.1:${CONTROL_PORTAL_PORT}}"
USER_URL="${DENSE_MEM_USER_URL:-http://127.0.0.1:${DENSE_MEM_PORT}}"
PROMETHEUS_URL="${DENSE_MEM_PROMETHEUS_URL:-http://127.0.0.1:${PROMETHEUS_PORT}}"
export DENSE_MEM_PORT CONTROL_PORTAL_PORT PROMETHEUS_PORT PROMETHEUS_CONTAINER_NAME
export POSTGRES_HOST_PORT NEO4J_HTTP_HOST_PORT NEO4J_BOLT_HOST_PORT REDIS_PORT

TEMP_DIR="$(mktemp -d)"
cd "$ROOT_DIR"
trap cleanup EXIT

prepare_e2e_environment
chmod 600 "$E2E_ENV_FILE"
require_env_true TELEMETRY_ENABLED
require_env_value AI_API_URL >/dev/null
require_env_value AI_API_KEY >/dev/null
require_env_value AI_API_EMBEDDING_MODEL >/dev/null
require_env_value AI_API_EMBEDDING_DIMENSIONS >/dev/null
if [[ "$E2E_SCENARIO" == "submission_status" || "$E2E_SCENARIO" == "security_intake" || "$E2E_SCENARIO" == "submission_assessment" || "$E2E_SCENARIO" == "semantic_holds" || "${DENSE_MEM_E2E_REQUIRE_LIVE_DREAM_PROVIDER:-0}" == "1" ]]; then
  require_env_value AI_VERIFIER_API_URL >/dev/null
  require_env_value AI_VERIFIER_API_KEY >/dev/null
  require_env_value AI_VERIFIER_MODEL >/dev/null
fi
CONTROL_TOKEN="$(require_env_value CONTROL_PORTAL_TOKEN)"
TELEMETRY_SCRAPE_TOKEN="$(require_env_value TELEMETRY_SCRAPE_TOKEN)"

DOCKER_PLUGIN_SOURCE_CONFIG="${DOCKER_CONFIG:-${HOME}/.docker}"
if [[ -z "${DENSE_MEM_E2E_DOCKER_CONFIG:-}" ]]; then
  mkdir "${TEMP_DIR}/docker-config"
  printf '{}\n' > "${TEMP_DIR}/docker-config/config.json"
  if [[ -x "${DOCKER_PLUGIN_SOURCE_CONFIG}/cli-plugins/docker-buildx" ]]; then
    mkdir "${TEMP_DIR}/docker-config/cli-plugins"
    ln -s \
      "${DOCKER_PLUGIN_SOURCE_CONFIG}/cli-plugins/docker-buildx" \
      "${TEMP_DIR}/docker-config/cli-plugins/docker-buildx"
  fi
  export DOCKER_CONFIG="${TEMP_DIR}/docker-config"
else
  export DOCKER_CONFIG="$DENSE_MEM_E2E_DOCKER_CONFIG"
fi
if ! docker buildx version >/dev/null 2>&1; then
  echo "Docker Buildx is required for compose e2e image builds." >&2
  exit 1
fi
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

if [[ "$E2E_MODE" == "entra_scim" ]]; then
  echo "Skipping unrelated compose prechecks for the Entra SCIM scenario."
elif [[ "$E2E_SCENARIO" == "portal" ]]; then
  echo "Skipping unrelated disposable PostgreSQL prechecks for the portal scenario."
elif [[ "${DENSE_MEM_E2E_SKIP_PRECHECKS:-0}" == "1" ]]; then
  echo "Skipping disposable PostgreSQL prechecks by DENSE_MEM_E2E_SKIP_PRECHECKS."
else
  echo "Running disposable PostgreSQL SSO and evidence-grounded Dreams regressions."
  DENSE_MEM_REPOSITORY_TESTCONTAINERS=1 go test \
    ./internal/repository \
    ./internal/http \
    -run '^(TestSSORuntimeEntitlementsExcludeArchivedTeams|TestDreamControlRepositoryIsTeamScopedAndAuditsAtomicRefresh|TestDreamRepositoryPersistsEvidenceGroundedHypothesisAndPathAssessment|TestScheduledDreamRecoveryFencesExpiredLease|TestScheduledDreamsAreTeamOwnedAndFeedbackIsActorAudited|TestSSOOIDCCallbackSkipsArchivedTeamMappingIntegration)$' \
    -count=1
fi

prepare_e2e_compose_files
prepare_postgres_e2e_overlay
prepare_e2e_prometheus_files
prepare_entra_mock_files

if ! compose config -q; then
  echo "Generated E2E compose configuration is invalid." >&2
  exit 1
fi

echo "Preparing isolated e2e compose project ${COMPOSE_PROJECT_NAME} from ${COMPOSE_SOURCE_FILE} using code from ${ROOT_DIR}."
if ! compose down -v --remove-orphans >/dev/null; then
  echo "Failed to reset e2e compose project ${COMPOSE_PROJECT_NAME} before startup." >&2
  exit 1
fi
remove_e2e_images

if docker ps -a --format '{{.Names}}' | grep -Fxq "$PROMETHEUS_CONTAINER_NAME"; then
  echo "Container ${PROMETHEUS_CONTAINER_NAME} already exists; choose another DENSE_MEM_E2E_PROJECT_NAME." >&2
  exit 1
fi

echo "Starting e2e compose stack on ${USER_URL}, ${CONTROL_URL}, and ${PROMETHEUS_URL}."
compose up -d postgres
wait_for_postgres_service
provision_postgres_runtime_role
compose up -d --build

wait_for_url "main API readiness" "${USER_URL}/ready"
wait_for_url "control portal API" "${CONTROL_URL}/control/api/session" "Authorization: Bearer ${CONTROL_TOKEN}"
verify_postgres_runtime_migration_state
if [[ "$E2E_MODE" != "entra_scim" ]]; then
  wait_for_url "Prometheus readiness" "${PROMETHEUS_URL}/-/ready"
fi

if [[ "$E2E_MODE" == "entra_scim" ]]; then
  wait_for_entra_mock
  echo "Running compose-backed Entra OIDC and SCIM e2e."
  NODE_EXTRA_CA_CERTS="${E2E_ENTRA_DIR}/ca.pem" \
  DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
  DENSE_MEM_USER_URL="$USER_URL" \
  DENSE_MEM_CONTROL_TOKEN="$CONTROL_TOKEN" \
  DENSE_MEM_ENTRA_MOCK_URL="https://localhost:${E2E_ENTRA_PORT}" \
  node "$ROOT_DIR/tests/uat/entra_scim_e2e.mjs"
  exit 0
fi

echo "Seeding e2e team through the private control API."
create_control_team "E2E Team" "compose e2e seed"
team_id="$CREATED_TEAM_ID"
create_control_profile "$team_id" "E2E Profile"
api_key="$CREATED_API_KEY"

if [[ "$E2E_SCENARIO" == "portal" ]]; then
  echo "Running compose-backed API-key portal cookie-auth e2e."
  dream_statement="portal cookie-auth e2e"
  DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
  DENSE_MEM_USER_URL="$USER_URL" \
  DENSE_MEM_CONTROL_TOKEN="$CONTROL_TOKEN" \
  DENSE_MEM_E2E_TEAM_ID="$team_id" \
  DENSE_MEM_E2E_API_KEY="$api_key" \
  DENSE_MEM_E2E_TEAM_NAME="E2E Team" \
  DENSE_MEM_E2E_DREAM_STATEMENT="$dream_statement" \
  DENSE_MEM_PROMETHEUS_URL="$PROMETHEUS_URL" \
  run_compose_playwright_tests portal
  exit 0
fi

if [[ "$E2E_SCENARIO" == "mcp_boundaries" ]]; then
  echo "Running compose-backed MCP production/evaluation and feature-gate boundary e2e."
  DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
  DENSE_MEM_USER_URL="$USER_URL" \
  DENSE_MEM_CONTROL_TOKEN="$CONTROL_TOKEN" \
  DENSE_MEM_E2E_TEAM_ID="$team_id" \
  DENSE_MEM_E2E_API_KEY="$api_key" \
  node "$ROOT_DIR/tests/uat/mcp_boundaries_e2e.mjs"
  exit 0
fi

if [[ "$E2E_SCENARIO" == "security_intake" ]]; then
  echo "Running compose-backed security intake e2e with the configured live verifier."
  DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
  DENSE_MEM_USER_URL="$USER_URL" \
  DENSE_MEM_CONTROL_TOKEN="$CONTROL_TOKEN" \
  DENSE_MEM_E2E_TEAM_ID="$team_id" \
  DENSE_MEM_E2E_API_KEY="$api_key" \
  DENSE_MEM_PROMETHEUS_URL="$PROMETHEUS_URL" \
  DENSE_MEM_E2E_COMPOSE_PROJECT="$COMPOSE_PROJECT_NAME" \
  DENSE_MEM_E2E_COMPOSE_FILE="$COMPOSE_FILE" \
  node "$ROOT_DIR/tests/uat/security_intake_mcp_e2e.mjs"
  exit 0
fi

if [[ "$E2E_SCENARIO" == "submission_status" ]]; then
  echo "Running compose-backed submission status and public-contract e2e with the configured live verifier."
  DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
  DENSE_MEM_CONTROL_TOKEN="$CONTROL_TOKEN" \
  DENSE_MEM_USER_URL="$USER_URL" \
  DENSE_MEM_E2E_TEAM_ID="$team_id" \
  DENSE_MEM_E2E_API_KEY="$api_key" \
  DENSE_MEM_E2E_COMPOSE_PROJECT="$COMPOSE_PROJECT_NAME" \
  DENSE_MEM_E2E_COMPOSE_FILE="$COMPOSE_FILE" \
  node "$ROOT_DIR/tests/uat/submission_status_mcp_e2e.mjs"
  exit 0
fi

if [[ "$E2E_SCENARIO" == "submission_assessment" ]]; then
  echo "Running compose-backed submission-wide assessor e2e with the configured live verifier."
  DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
  DENSE_MEM_USER_URL="$USER_URL" \
  DENSE_MEM_E2E_TEAM_ID="$team_id" \
  DENSE_MEM_E2E_API_KEY="$api_key" \
  DENSE_MEM_PROMETHEUS_URL="$PROMETHEUS_URL" \
  DENSE_MEM_E2E_COMPOSE_PROJECT="$COMPOSE_PROJECT_NAME" \
  DENSE_MEM_E2E_COMPOSE_FILE="$COMPOSE_FILE" \
  node "$ROOT_DIR/tests/uat/submission_assessment_mcp_e2e.mjs"
  exit 0
fi

if [[ "$E2E_SCENARIO" == "semantic_holds" ]]; then
  echo "Running compose-backed semantic-hold and replacement e2e with the configured live verifier."
  DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
  DENSE_MEM_CONTROL_TOKEN="$CONTROL_TOKEN" \
  DENSE_MEM_USER_URL="$USER_URL" \
  DENSE_MEM_E2E_TEAM_ID="$team_id" \
  DENSE_MEM_E2E_API_KEY="$api_key" \
  DENSE_MEM_PROMETHEUS_URL="$PROMETHEUS_URL" \
  DENSE_MEM_E2E_COMPOSE_PROJECT="$COMPOSE_PROJECT_NAME" \
  DENSE_MEM_E2E_COMPOSE_FILE="$COMPOSE_FILE" \
  node "$ROOT_DIR/tests/uat/semantic_holds_mcp_e2e.mjs"
  exit 0
fi

echo "Running compose-backed scheduled team dreaming e2e."
dream_json="$(DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
DENSE_MEM_USER_URL="$USER_URL" \
DENSE_MEM_CONTROL_TOKEN="$CONTROL_TOKEN" \
DENSE_MEM_E2E_TEAM_ID="$team_id" \
DENSE_MEM_E2E_API_KEY="$api_key" \
DENSE_MEM_E2E_COMPOSE_PROJECT="$COMPOSE_PROJECT_NAME" \
DENSE_MEM_E2E_COMPOSE_FILE="$COMPOSE_FILE" \
node "$ROOT_DIR/tests/uat/team_dreaming_e2e.mjs")"
printf '%s\n' "$dream_json"
dream_statement="$(printf '%s' "$dream_json" | json_field statement)"

echo "Running compose-backed telemetry MCP e2e."
DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
DENSE_MEM_USER_URL="$USER_URL" \
DENSE_MEM_CONTROL_TOKEN="$CONTROL_TOKEN" \
DENSE_MEM_E2E_TEAM_ID="$team_id" \
DENSE_MEM_E2E_API_KEY="$api_key" \
DENSE_MEM_PROMETHEUS_URL="$PROMETHEUS_URL" \
node "$ROOT_DIR/tests/uat/telemetry_mcp_e2e.mjs"

if [[ "${DENSE_MEM_E2E_SKIP_PLAYWRIGHT:-0}" == "1" ]]; then
  echo "Skipping compose-backed Playwright tests by DENSE_MEM_E2E_SKIP_PLAYWRIGHT."
else
  echo "Running compose-backed Playwright tests."
  run_compose_playwright_tests
fi

echo "Running compose-backed MCP conflict e2e."
echo "Seeding isolated conflict e2e team through the private control API."
create_control_team "Conflict E2E Team" "compose conflict e2e seed"
conflict_team_id="$CREATED_TEAM_ID"
DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
DENSE_MEM_USER_URL="$USER_URL" \
DENSE_MEM_CONTROL_TOKEN="$CONTROL_TOKEN" \
DENSE_MEM_E2E_TEAM_ID="$conflict_team_id" \
DENSE_MEM_E2E_COMPOSE_PROJECT="$COMPOSE_PROJECT_NAME" \
DENSE_MEM_E2E_COMPOSE_FILE="$COMPOSE_FILE" \
node "$ROOT_DIR/tests/uat/conflict_mcp_e2e.mjs"
