#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="${ROOT_DIR}/docker-compose.yml"
ROOT_ENV_FILE="${ROOT_DIR}/.env"
E2E_MARKER="# dense-mem e2e generated by scripts/e2e-compose.sh"
TEMP_DIR=""
E2E_FILES_PREPARED=0
E2E_ENV_FILE=""
E2E_COMPOSE_FILE=""
E2E_PROMETHEUS_DIR=""
E2E_BIND_DIR=""
E2E_FILE_ID=""

sanitize_project_name() {
  local raw="$1"
  local sanitized
  sanitized="$(printf '%s' "$raw" | tr '[:upper:]_' '[:lower:]-' | tr -cd 'a-z0-9-' | sed -e 's/--*/-/g' -e 's/^-//' -e 's/-$//')"
  if [[ -z "$sanitized" ]]; then
    sanitized="densemem-e2e"
  fi
  printf '%s' "$sanitized"
}

pick_ports() {
  local count="$1"
  node - "$count" <<'NODE'
const net = require("node:net");
const count = Number(process.argv[2]);
const servers = [];

function listen() {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      servers.push(server);
      resolve(server.address().port);
    });
  });
}

(async () => {
  const ports = [];
  for (let i = 0; i < count; i += 1) {
    ports.push(await listen());
  }
  console.log(ports.join(" "));
  for (const server of servers) {
    server.close();
  }
})().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
NODE
}

json_field() {
  local field="$1"
  node -e '
let input = "";
process.stdin.on("data", chunk => input += chunk);
process.stdin.on("end", () => {
  const value = JSON.parse(input)[process.argv[1]];
  if (value === undefined || value === null || value === "") {
    process.exit(1);
  }
  process.stdout.write(String(value));
});
' "$field"
}

env_file_value() {
  local field="$1"
  node - "$ROOT_ENV_FILE" "$field" <<'NODE'
const fs = require("node:fs");
const path = process.argv[2];
const target = process.argv[3];

function decodeValue(raw) {
  const value = raw.trim();
  if (value.startsWith('"') || value.startsWith("'")) {
    const quote = value[0];
    const closing = closingQuoteIndex(value, quote);
    if (closing > 0) {
      const inner = value.slice(1, closing);
      if (quote === "'") {
        return inner;
      }
      return inner
        .replace(/\\n/g, "\n")
        .replace(/\\r/g, "\r")
        .replace(/\\t/g, "\t")
        .replace(/\\"/g, '"')
        .replace(/\\\\/g, "\\");
    }
  }
  return stripInlineComment(value).trim();
}

function closingQuoteIndex(value, quote) {
  for (let index = 1; index < value.length; index += 1) {
    if (quote === '"' && value[index] === "\\" && index + 1 < value.length) {
      index += 1;
      continue;
    }
    if (value[index] === quote) {
      return index;
    }
  }
  return -1;
}

function stripInlineComment(value) {
  for (let index = 0; index < value.length; index += 1) {
    if (value[index] === "#" && (index === 0 || /\s/.test(value[index - 1]))) {
      return value.slice(0, index);
    }
  }
  return value;
}

let resolved;
for (const line of fs.readFileSync(path, "utf8").split(/\r?\n/)) {
  const match = line.match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
  if (!match || match[1] !== target) {
    continue;
  }
  resolved = decodeValue(match[2]);
}
if (resolved !== undefined) {
  process.stdout.write(resolved);
} else {
  process.exit(1);
}
NODE
}

require_env_value() {
  local field="$1"
  local value=""
  if ! value="$(env_file_value "$field")" || [[ -z "$value" ]]; then
    echo "Missing required ${field} in ${ROOT_ENV_FILE}." >&2
    return 1
  fi
  printf '%s' "$value"
}

require_env_true() {
  local field="$1"
  local value=""
  value="$(require_env_value "$field")"
  case "$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')" in
    true|1|yes|y|on)
      return 0
      ;;
  esac
  echo "${field} must be true in ${ROOT_ENV_FILE} for compose e2e." >&2
  return 1
}

wait_for_url() {
  local label="$1"
  local url="$2"
  local header="${3:-}"
  for _ in $(seq 1 90); do
    if [[ -n "$header" ]]; then
      if curl -fsS -H "$header" "$url" >/dev/null 2>&1; then
        return 0
      fi
    elif curl -fsS "$url" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "Timed out waiting for ${label} at ${url}" >&2
  return 1
}

compose() {
  docker compose -p "$COMPOSE_PROJECT_NAME" -f "$COMPOSE_FILE" "$@"
}

is_generated_marker_file() {
  local path="$1"
  local first_line=""
  if [[ ! -f "$path" ]]; then
    return 1
  fi
  IFS= read -r first_line < "$path" || true
  [[ "$first_line" == "$E2E_MARKER" ]]
}

prepare_e2e_prometheus_files() {
  if [[ -e "$E2E_PROMETHEUS_DIR" ]]; then
    echo "Refusing to replace existing E2E Prometheus directory ${E2E_PROMETHEUS_DIR}." >&2
    return 1
  fi
  mkdir "$E2E_PROMETHEUS_DIR"
  chmod 755 "$E2E_PROMETHEUS_DIR"
  E2E_FILES_PREPARED=1

  cat > "${E2E_PROMETHEUS_DIR}/prometheus.yml" <<EOF
${E2E_MARKER}
global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: dense-mem
    metrics_path: /metrics
    authorization:
      credentials_file: /etc/prometheus/telemetry-scrape-token
    static_configs:
      - targets:
          - server:8090
EOF

  printf '%s\n' "$TELEMETRY_SCRAPE_TOKEN" > "${E2E_PROMETHEUS_DIR}/telemetry-scrape-token"
  chmod 644 "${E2E_PROMETHEUS_DIR}/prometheus.yml" "${E2E_PROMETHEUS_DIR}/telemetry-scrape-token"
}

prepare_e2e_compose_files() {
  if [[ ! -f "$COMPOSE_FILE" ]]; then
    echo "Missing supported compose source at ${COMPOSE_FILE}." >&2
    return 1
  fi
  E2E_ENV_FILE="${ROOT_DIR}/.env.e2e-${E2E_FILE_ID}"
  E2E_COMPOSE_FILE="${ROOT_DIR}/docker-compose.e2e-${E2E_FILE_ID}.yml"
  printf '%s\n' "$E2E_MARKER" > "$E2E_ENV_FILE"
  awk '
    /^[[:space:]]*(export[[:space:]]+)?NEO4J_[A-Za-z0-9_]*[[:space:]]*=/ { next }
    { print }
  ' "$ROOT_ENV_FILE" >> "$E2E_ENV_FILE"
  node - "$COMPOSE_FILE" "$E2E_COMPOSE_FILE" "$E2E_ENV_FILE" "$E2E_PROMETHEUS_DIR" "$E2E_MARKER" <<'NODE'
const fs = require("node:fs");

const [sourcePath, destinationPath, envFile, prometheusDir, marker] = process.argv.slice(2);
let compose = fs.readFileSync(sourcePath, "utf8");

function replaceRequired(pattern, replacement, label, expectedCount) {
  let count = 0;
  compose = compose.replace(pattern, (...args) => {
    count += 1;
    return typeof replacement === "function" ? replacement(...args) : replacement;
  });
  if ((expectedCount === undefined && count === 0) || (expectedCount !== undefined && count !== expectedCount)) {
    const expected = expectedCount === undefined ? "at least one" : expectedCount;
    throw new Error(`expected ${expected} ${label} replacement(s), found ${count}`);
  }
}

replaceRequired(/^(\s*-\s*)\.env\s*$/gm, (_, prefix) => `${prefix}${envFile}`, "env_file");
replaceRequired(
  /^(\s*)-\s+\.\/?prometheus\.yml:\/etc\/prometheus\/prometheus\.yml:ro\s*$/m,
  (_, indent) => `${indent}- ${prometheusDir}:/etc/prometheus:ro`,
  "Prometheus config mount",
);
replaceRequired(
  /(^  prometheus:\r?\n[\s\S]*?)^    secrets:\r?\n      - telemetry-scrape-token\r?\n/m,
  (_, prometheusBlock) => prometheusBlock,
  "Prometheus secret block",
);
replaceRequired(
  /^secrets:\r?\n  telemetry-scrape-token:\r?\n    file: \.\/?telemetry-scrape-token\r?\n(?:\r?\n)?/m,
  "",
  "top-level telemetry secret",
);

fs.writeFileSync(destinationPath, `${marker}\n${compose}`);
NODE
  if ! grep -F -- "$E2E_ENV_FILE" "$E2E_COMPOSE_FILE" >/dev/null || ! grep -F -- "${E2E_PROMETHEUS_DIR}:/etc/prometheus:ro" "$E2E_COMPOSE_FILE" >/dev/null; then
    echo "Generated compose file did not contain the expected E2E substitutions." >&2
    return 1
  fi
  COMPOSE_FILE="$E2E_COMPOSE_FILE"
}

restore_root_files() {
  if [[ "$E2E_FILES_PREPARED" != "1" || ! -d "$E2E_PROMETHEUS_DIR" ]]; then
    return
  fi
  if is_generated_marker_file "${E2E_PROMETHEUS_DIR}/prometheus.yml"; then
    rm -r "$E2E_PROMETHEUS_DIR"
  fi
}

cleanup() {
  local status=$?
  set +e
  if [[ "$E2E_FILES_PREPARED" == "1" && "${DENSE_MEM_E2E_KEEP_COMPOSE:-0}" != "1" ]]; then
    if ! compose down -v --remove-orphans >/dev/null; then
      echo "Failed to clean up e2e compose project ${COMPOSE_PROJECT_NAME}." >&2
    fi
    sleep 1
  elif [[ "${DENSE_MEM_E2E_KEEP_COMPOSE:-0}" == "1" ]]; then
    echo "Keeping e2e compose project ${COMPOSE_PROJECT_NAME}."
  fi
  restore_root_files
  if [[ -n "$E2E_ENV_FILE" && -f "$E2E_ENV_FILE" ]] && is_generated_marker_file "$E2E_ENV_FILE"; then
    rm -- "$E2E_ENV_FILE"
  fi
  if [[ -n "$E2E_COMPOSE_FILE" && -f "$E2E_COMPOSE_FILE" ]] && is_generated_marker_file "$E2E_COMPOSE_FILE"; then
    rm -- "$E2E_COMPOSE_FILE"
  fi
  if [[ -n "$TEMP_DIR" && -d "$TEMP_DIR" ]]; then
    rm -r "$TEMP_DIR"
  fi
  exit "$status"
}

if [[ ! -f "$COMPOSE_FILE" ]]; then
  echo "Missing docker-compose.yml at ${COMPOSE_FILE}." >&2
  exit 1
fi

if [[ ! -f "$ROOT_ENV_FILE" ]]; then
  echo "Missing .env at ${ROOT_ENV_FILE}; compose e2e uses the local .env file." >&2
  exit 1
fi

E2E_RUN_ID="${DENSE_MEM_E2E_RUN_ID:-$(date -u +%Y%m%d%H%M%S)-$$}"
E2E_FILE_ID="$(sanitize_project_name "$E2E_RUN_ID")"
COMPOSE_PROJECT_NAME="$(sanitize_project_name "${DENSE_MEM_E2E_PROJECT_NAME:-densemem-e2e-${E2E_RUN_ID}}")"
# Docker Desktop may need a bind-mountable directory outside a /tmp worktree.
E2E_BIND_DIR="${DENSE_MEM_E2E_BIND_DIR:-${ROOT_DIR}}"
if [[ ! -d "$E2E_BIND_DIR" || ! -w "$E2E_BIND_DIR" ]]; then
  echo "DENSE_MEM_E2E_BIND_DIR must be an existing writable directory: ${E2E_BIND_DIR}." >&2
  exit 1
fi
E2E_PROMETHEUS_DIR="${E2E_BIND_DIR}/densemem-e2e-prometheus-${E2E_FILE_ID}"
read -r \
  generated_api_port \
  generated_control_port \
  generated_prometheus_port \
  generated_postgres_port \
  generated_neo4j_http_port \
  generated_neo4j_bolt_port \
  generated_redis_port < <(pick_ports 7)
DENSE_MEM_PORT="${DENSE_MEM_E2E_API_PORT:-$generated_api_port}"
CONTROL_PORTAL_PORT="${DENSE_MEM_E2E_CONTROL_PORT:-$generated_control_port}"
PROMETHEUS_PORT="${DENSE_MEM_E2E_PROMETHEUS_PORT:-$generated_prometheus_port}"
POSTGRES_HOST_PORT="${DENSE_MEM_E2E_POSTGRES_PORT:-$generated_postgres_port}"
NEO4J_HTTP_HOST_PORT="${DENSE_MEM_E2E_NEO4J_HTTP_PORT:-$generated_neo4j_http_port}"
NEO4J_BOLT_HOST_PORT="${DENSE_MEM_E2E_NEO4J_BOLT_PORT:-$generated_neo4j_bolt_port}"
REDIS_PORT="${DENSE_MEM_E2E_REDIS_PORT:-$generated_redis_port}"
PROMETHEUS_CONTAINER_NAME="${DENSE_MEM_E2E_PROMETHEUS_CONTAINER_NAME:-${COMPOSE_PROJECT_NAME}-prometheus}"
CONTROL_URL="${DENSE_MEM_CONTROL_URL:-http://127.0.0.1:${CONTROL_PORTAL_PORT}}"
USER_URL="${DENSE_MEM_USER_URL:-http://127.0.0.1:${DENSE_MEM_PORT}}"
PROMETHEUS_URL="${DENSE_MEM_PROMETHEUS_URL:-http://127.0.0.1:${PROMETHEUS_PORT}}"
export DENSE_MEM_PORT CONTROL_PORTAL_PORT PROMETHEUS_PORT PROMETHEUS_CONTAINER_NAME
export POSTGRES_HOST_PORT NEO4J_HTTP_HOST_PORT NEO4J_BOLT_HOST_PORT REDIS_PORT

require_env_true TELEMETRY_ENABLED
require_env_value AI_API_URL >/dev/null
require_env_value AI_API_KEY >/dev/null
require_env_value AI_API_EMBEDDING_MODEL >/dev/null
require_env_value AI_API_EMBEDDING_DIMENSIONS >/dev/null
CONTROL_TOKEN="$(require_env_value CONTROL_PORTAL_TOKEN)"
TELEMETRY_SCRAPE_TOKEN="$(require_env_value TELEMETRY_SCRAPE_TOKEN)"

TEMP_DIR="$(mktemp -d)"

if [[ -z "${DENSE_MEM_E2E_DOCKER_CONFIG:-}" ]]; then
  mkdir "${TEMP_DIR}/docker-config"
  printf '{}\n' > "${TEMP_DIR}/docker-config/config.json"
  export DOCKER_CONFIG="${TEMP_DIR}/docker-config"
else
  export DOCKER_CONFIG="$DENSE_MEM_E2E_DOCKER_CONFIG"
fi
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

cd "$ROOT_DIR"
trap cleanup EXIT

if [[ "${DENSE_MEM_E2E_SKIP_PRECHECKS:-0}" == "1" ]]; then
  echo "Skipping disposable PostgreSQL prechecks by DENSE_MEM_E2E_SKIP_PRECHECKS."
else
  echo "Running disposable PostgreSQL SSO and Dreams regressions."
  DENSE_MEM_REPOSITORY_TESTCONTAINERS=1 go test \
    ./internal/repository \
    ./internal/http \
    -run '^(TestSSORuntimeEntitlementsExcludeArchivedTeams|TestDreamControlRepositoryIsTeamScopedAndAuditsAtomicRefresh|TestSSOOIDCCallbackSkipsArchivedTeamMappingIntegration)$' \
    -count=1
fi

prepare_e2e_compose_files
prepare_e2e_prometheus_files

if ! compose config -q; then
  echo "Generated E2E compose configuration is invalid." >&2
  exit 1
fi

echo "Preparing isolated e2e compose project ${COMPOSE_PROJECT_NAME} from docker-compose.yml."
if ! compose down -v --remove-orphans >/dev/null; then
  echo "Failed to reset e2e compose project ${COMPOSE_PROJECT_NAME} before startup." >&2
  exit 1
fi

if docker ps -a --format '{{.Names}}' | grep -Fxq "$PROMETHEUS_CONTAINER_NAME"; then
  echo "Container ${PROMETHEUS_CONTAINER_NAME} already exists; choose another DENSE_MEM_E2E_PROJECT_NAME." >&2
  exit 1
fi

echo "Starting e2e compose stack on ${USER_URL}, ${CONTROL_URL}, and ${PROMETHEUS_URL}."
compose up -d --build

wait_for_url "main API readiness" "${USER_URL}/ready"
wait_for_url "control portal API" "${CONTROL_URL}/control/api/session" "Authorization: Bearer ${CONTROL_TOKEN}"
wait_for_url "Prometheus readiness" "${PROMETHEUS_URL}/-/ready"

echo "Seeding e2e team through the compose server container."
seed_json="$(compose exec -T server /app/provision-team --name "E2E Team" --description "compose e2e seed" --rate-limit 300)"
team_id="$(printf '%s' "$seed_json" | json_field team_id)"
api_key="$(printf '%s' "$seed_json" | json_field api_key)"

if [[ "${DENSE_MEM_E2E_SKIP_PLAYWRIGHT:-0}" == "1" ]]; then
  echo "Skipping compose-backed Playwright tests by DENSE_MEM_E2E_SKIP_PLAYWRIGHT."
else
  echo "Running compose-backed Playwright tests."
  DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
  DENSE_MEM_USER_URL="$USER_URL" \
  DENSE_MEM_CONTROL_TOKEN="$CONTROL_TOKEN" \
  DENSE_MEM_E2E_TEAM_ID="$team_id" \
  DENSE_MEM_E2E_TEAM_NAME="E2E Team" \
  DENSE_MEM_E2E_API_KEY="$api_key" \
  DENSE_MEM_PROMETHEUS_URL="$PROMETHEUS_URL" \
  npm --prefix "$ROOT_DIR/web" run playwright:compose
fi

echo "Running compose-backed MCP conflict e2e."
DENSE_MEM_CONTROL_URL="$CONTROL_URL" \
DENSE_MEM_USER_URL="$USER_URL" \
DENSE_MEM_CONTROL_TOKEN="$CONTROL_TOKEN" \
DENSE_MEM_E2E_TEAM_ID="$team_id" \
DENSE_MEM_E2E_COMPOSE_PROJECT="$COMPOSE_PROJECT_NAME" \
DENSE_MEM_E2E_COMPOSE_FILE="$COMPOSE_FILE" \
node "$ROOT_DIR/tests/uat/conflict_mcp_e2e.mjs"
