package config

// ConfigProvider is the companion interface for Config.
// Consumers and tests depend on this abstraction rather than the concrete struct.
type ConfigProvider interface {
	GetPostgresDSN() string
	GetPostgresMaxOpenConns() int
	GetPostgresMaxIdleConns() int
	GetPostgresConnMaxLifetimeSeconds() int
	GetPostgresVectorMaxConcurrency() int
	GetPGVectorExtensionRequired() bool
	GetPostgresStatementTimeoutSeconds() int
	GetPostgresLockTimeoutSeconds() int
	GetNeo4jURI() string
	GetNeo4jUser() string
	GetNeo4jPassword() string
	GetNeo4jDatabase() string
	GetRedisAddr() string
	GetRedisPassword() string
	GetRedisDB() int
	GetHTTPMaxBodyBytes() int
	GetRateLimitPerMinute() int
	GetFragmentCreateRateLimit() int
	GetFragmentReadRateLimit() int
	GetSSEHeartbeatSeconds() int
	GetSSEMaxDurationSeconds() int
	GetSSEMaxConcurrentStreams() int
	GetEmbeddingDimensions() int
	GetAIAPIURL() string
	GetAIAPIKey() string
	GetAIEmbeddingModel() string
	GetAIEmbeddingDimensions() int
	GetAIEmbeddingTimeoutSeconds() int
	GetAIEmbeddingMaxConcurrency() int
	IsEmbeddingConfigured() bool
	GetAIVerifierAPIURL() string
	GetAIVerifierAPIKey() string
	GetAIReviewerModel() string
	GetAIVerifierModel() string
	GetAIVerifierTimeoutSeconds() int
	GetAIVerifierMaxConcurrency() int
	GetAIVerifierCooldownPollSeconds() int
	GetAIVerifierMaxEntityResults() int
	GetAIVerifierMaxRelationshipResults() int
	GetAIVerifierMaxInputBytes() int
	GetAIVerifierMaxOutputBytes() int
	GetAIVerifierMaxResponseRegenerations() int
	GetRelationshipMatchMaxCandidates() int
	GetMemoryPlacementWorkerCount() int
	GetMemoryPlacementLeaseSeconds() int
	GetMemoryPlacementHeartbeatSeconds() int
	GetMemoryPlacementPollSeconds() int
	GetMemoryPlacementMaxAttempts() int
	GetEmbeddingWorkerCount() int
	GetEmbeddingBatchSize() int
	GetEmbeddingJobLeaseSeconds() int
	GetEmbeddingJobPollSeconds() int
	GetEmbeddingJobMaxAttempts() int
	GetEmbeddingJobRetryMaxSeconds() int
	GetEmbeddingPendingStaleSeconds() int
	GetSearchDocumentFormatVersion() string
	GetEmbeddingNormalizationVersion() string
	GetPGVectorDistance() string
	GetPGVectorANNStrategy() string
	GetPGVectorHNSWM() int
	GetPGVectorHNSWEFConstruction() int
	GetPGVectorIndexBuildMaxConcurrency() int
	GetRecallRRFEnabled() bool
	GetRecallRRFK() int
	GetRecallRRFBranchWeights() string
	GetRecallBranchPriority() string
	GetRecallBranchLimitMultiplier() int
	GetRecallBranchLimitFloor() int
	GetRecallBranchLimitMax() int
	GetRecallDeterministicRerankEnabled() bool
	GetRecallMaxEntitySeeds() int
	GetRecallDiscoveryRelationshipsPerEvidence() int
	GetRecallMaxGraphDepth() int
	GetRecallMaxEdges() int
	GetRecallGraphTimeoutMilliseconds() int
	GetRecallRequiredBranchProfile() string
	GetPGVectorExactFilteredMaxRows() int
	GetPGVectorHNSWEFSearch() int
	GetPGVectorHNSWIterativeScan() string
	GetPGVectorHNSWMaxScanTuples() int
	GetPGVectorHNSWScanMemMultiplier() int
	GetPredicateRegistryVersion() string
	GetPredicateRegistryCacheTTLSeconds() int
	GetPredicateUnknownAction() string
	GetRedisTLSEnabled() bool
	GetDistributedCoordinationRequired() bool
	GetRememberRateLimitPerMinute() int
	GetRecallRateLimitPerMinute() int
	GetTraceRateLimitPerMinute() int
	GetClaimWriteRateLimit() int
	GetClaimReadRateLimit() int
	GetRecallValidatedClaimWeight() float64
	GetPromoteTxTimeoutSeconds() int
	GetMemoryPackImportHistoryDays() int
	GetSkillPackImportHistoryDays() int
	GetAICommunityMaxNodes() int
	GetControlHTTPAddr() string
	GetControlPortalToken() string
	GetV2BootMode() string
}
