package config

import "testing"

func TestConfigProviderInterface(t *testing.T) {
	clearEnv()
	setRequiredEnv()

	cfg, err := Load()
	if err != nil {
		t.Fatalf("Load() returned unexpected error: %v", err)
	}

	var provider ConfigProvider = &cfg
	_ = provider.GetPostgresDSN()
	_ = provider.GetNeo4jURI()
	_ = provider.GetNeo4jUser()
	_ = provider.GetNeo4jPassword()
	_ = provider.GetNeo4jDatabase()
	_ = provider.GetRedisAddr()
	_ = provider.GetRedisPassword()
	_ = provider.GetRedisDB()
	_ = provider.GetHTTPMaxBodyBytes()
	_ = provider.GetRateLimitPerMinute()
	_ = provider.GetFragmentCreateRateLimit()
	_ = provider.GetFragmentReadRateLimit()
	_ = provider.GetSSEHeartbeatSeconds()
	_ = provider.GetSSEMaxDurationSeconds()
	_ = provider.GetSSEMaxConcurrentStreams()
	_ = provider.GetEmbeddingDimensions()
	_ = provider.GetAIAPIURL()
	_ = provider.GetAIAPIKey()
	_ = provider.GetAIEmbeddingModel()
	_ = provider.GetAIEmbeddingDimensions()
	_ = provider.GetAIEmbeddingTimeoutSeconds()
	_ = provider.IsEmbeddingConfigured()
	_ = provider.GetAIVerifierAPIURL()
	_ = provider.GetAIVerifierAPIKey()
	_ = provider.GetAIVerifierModel()
	_ = provider.GetAIVerifierTimeoutSeconds()
	_ = provider.GetAIVerifierMaxConcurrency()
	_ = provider.GetClaimWriteRateLimit()
	_ = provider.GetClaimReadRateLimit()
	_ = provider.GetRecallValidatedClaimWeight()
	_ = provider.GetPromoteTxTimeoutSeconds()
	_ = provider.GetMemoryPackImportHistoryDays()
	_ = provider.GetSkillPackImportHistoryDays()
	_ = provider.GetAICommunityMaxNodes()
	_ = provider.GetControlHTTPAddr()
	_ = provider.GetControlPortalToken()
	_ = provider.GetPostgresMaxOpenConns()
	_ = provider.GetPostgresMaxIdleConns()
	_ = provider.GetPostgresConnMaxLifetimeSeconds()
	_ = provider.GetPostgresVectorMaxConcurrency()
	_ = provider.GetPGVectorExtensionRequired()
	_ = provider.GetPostgresStatementTimeoutSeconds()
	_ = provider.GetPostgresLockTimeoutSeconds()
	_ = provider.GetAIEmbeddingMaxConcurrency()
	_ = provider.GetAIReviewerModel()
	_ = provider.GetAIVerifierCooldownPollSeconds()
	_ = provider.GetAIVerifierMaxEntityResults()
	_ = provider.GetAIVerifierMaxRelationshipResults()
	_ = provider.GetAIVerifierMaxInputBytes()
	_ = provider.GetAIVerifierMaxOutputBytes()
	_ = provider.GetAIVerifierMaxResponseRegenerations()
	_ = provider.GetRelationshipMatchMaxCandidates()
	_ = provider.GetMemoryPlacementWorkerCount()
	_ = provider.GetMemoryPlacementLeaseSeconds()
	_ = provider.GetMemoryPlacementHeartbeatSeconds()
	_ = provider.GetMemoryPlacementPollSeconds()
	_ = provider.GetMemoryPlacementMaxAttempts()
	_ = provider.GetEmbeddingWorkerCount()
	_ = provider.GetEmbeddingBatchSize()
	_ = provider.GetEmbeddingJobLeaseSeconds()
	_ = provider.GetEmbeddingJobPollSeconds()
	_ = provider.GetEmbeddingJobMaxAttempts()
	_ = provider.GetEmbeddingJobRetryMaxSeconds()
	_ = provider.GetEmbeddingPendingStaleSeconds()
	_ = provider.GetSearchDocumentFormatVersion()
	_ = provider.GetEmbeddingNormalizationVersion()
	_ = provider.GetPGVectorDistance()
	_ = provider.GetPGVectorANNStrategy()
	_ = provider.GetPGVectorHNSWM()
	_ = provider.GetPGVectorHNSWEFConstruction()
	_ = provider.GetPGVectorIndexBuildMaxConcurrency()
	_ = provider.GetRecallRRFEnabled()
	_ = provider.GetRecallRRFK()
	_ = provider.GetRecallRRFBranchWeights()
	_ = provider.GetRecallBranchPriority()
	_ = provider.GetRecallBranchLimitMultiplier()
	_ = provider.GetRecallBranchLimitFloor()
	_ = provider.GetRecallBranchLimitMax()
	_ = provider.GetRecallDeterministicRerankEnabled()
	_ = provider.GetRecallMaxEntitySeeds()
	_ = provider.GetRecallDiscoveryRelationshipsPerEvidence()
	_ = provider.GetRecallMaxGraphDepth()
	_ = provider.GetRecallMaxEdges()
	_ = provider.GetRecallGraphTimeoutMilliseconds()
	_ = provider.GetRecallRequiredBranchProfile()
	_ = provider.GetPGVectorExactFilteredMaxRows()
	_ = provider.GetPGVectorHNSWEFSearch()
	_ = provider.GetPGVectorHNSWIterativeScan()
	_ = provider.GetPGVectorHNSWMaxScanTuples()
	_ = provider.GetPGVectorHNSWScanMemMultiplier()
	_ = provider.GetPredicateRegistryVersion()
	_ = provider.GetPredicateRegistryCacheTTLSeconds()
	_ = provider.GetPredicateUnknownAction()
	_ = provider.GetRedisTLSEnabled()
	_ = provider.GetDistributedCoordinationRequired()
	_ = provider.GetRememberRateLimitPerMinute()
	_ = provider.GetRecallRateLimitPerMinute()
	_ = provider.GetTraceRateLimitPerMinute()
	_ = provider.GetV2BootMode()
}
