package search

import searchmaintenance "github.com/markhuangai/dense-mem/internal/search/maintenance"

type ActiveSearchContract = searchmaintenance.ActiveSearchContract
type EnsureActiveSearchContractInput = searchmaintenance.EnsureActiveSearchContractInput
type EnsureActiveSearchContractResult = searchmaintenance.EnsureActiveSearchContractResult
type SearchDocumentResult = searchmaintenance.SearchDocumentResult
type SearchDocumentForEmbedding = searchmaintenance.SearchDocumentForEmbedding
type UpsertSearchDocumentInput = searchmaintenance.UpsertSearchDocumentInput
type SearchDocumentEmbedding = searchmaintenance.SearchDocumentEmbedding
type SearchConvergenceInput = searchmaintenance.SearchConvergenceInput
type SearchConvergence = searchmaintenance.SearchConvergence
type SearchDocumentDriftCount = searchmaintenance.SearchDocumentDriftCount
type SearchReconciliationRun = searchmaintenance.SearchReconciliationRun
type SearchReconciliationSelectionInput = searchmaintenance.SearchReconciliationSelectionInput
type SearchReconciliationRunInput = searchmaintenance.SearchReconciliationRunInput
type FinishSearchReconciliationRunInput = searchmaintenance.FinishSearchReconciliationRunInput
type ApplySearchReconciliationInput = searchmaintenance.ApplySearchReconciliationInput
type SearchReconciliationApplyResult = searchmaintenance.SearchReconciliationApplyResult
type SearchReconciliationRepository = searchmaintenance.SearchReconciliationRepository
type SearchMaintenanceRepository = searchmaintenance.SearchMaintenanceRepository
