package dreamservice

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/markhuangai/dense-mem/internal/domain"
)

type HeuristicGenerator struct {
	model string
}

func NewHeuristicGenerator(model string) *HeuristicGenerator {
	if strings.TrimSpace(model) == "" {
		model = "dense-mem.heuristic-dream-v1"
	}
	return &HeuristicGenerator{model: model}
}

func (g *HeuristicGenerator) Model() string {
	return g.model
}

func (g *HeuristicGenerator) Generate(ctx context.Context, profileID string, req GenerateRequest) ([]GeneratedDream, error) {
	_ = ctx
	_ = profileID
	limit := req.MaxOutputs
	if limit <= 0 {
		limit = DefaultMaxOutputs
	}
	inputs := append([]DreamInput(nil), req.Inputs...)
	sort.SliceStable(inputs, func(i, j int) bool {
		if inputs[i].Type == inputs[j].Type {
			return inputs[i].ID < inputs[j].ID
		}
		return inputs[i].Type < inputs[j].Type
	})
	out := make([]GeneratedDream, 0, limit)
	seen := map[string]struct{}{}
	for i := 0; i < len(inputs) && len(out) < limit; i++ {
		for j := i + 1; j < len(inputs) && len(out) < limit; j++ {
			a := inputs[i]
			b := inputs[j]
			if a.ID == "" || b.ID == "" || a.ID == b.ID {
				continue
			}
			if a.Type == b.Type && a.Predicate == b.Predicate {
				continue
			}
			key := a.Type + ":" + a.ID + "|" + b.Type + ":" + b.ID
			if _, ok := seen[key]; ok {
				continue
			}
			seen[key] = struct{}{}
			out = append(out, dreamFromPair(a, b))
		}
	}
	return out, nil
}

func dreamFromPair(a, b DreamInput) GeneratedDream {
	aText := inputSummary(a)
	bText := inputSummary(b)
	likelihood := 0.35
	confidence := 0.45
	if a.Predicate != "" && b.Predicate != "" && a.Predicate != b.Predicate {
		likelihood += 0.1
	}
	return GeneratedDream{
		Hypothesis:      fmt.Sprintf("%s may be relevant when considering %s.", aText, bText),
		WhatIf:          fmt.Sprintf("What if %s and %s describe related pressure on the same workflow?", aText, bText),
		PossibleOutcome: fmt.Sprintf("If the relationship holds, future decisions involving %s should be checked against %s before use.", compactSubject(a), compactSubject(b)),
		Rationale:       "Generated by pairing same-team knowledge that is not already the same predicate/type, then keeping it as a hypothesis until user feedback confirms or rejects it.",
		Likelihood:      clamp01(likelihood),
		Confidence:      clamp01(confidence),
		SourceRefs: []domain.DreamSourceRef{
			{Type: a.Type, ID: a.ID},
			{Type: b.Type, ID: b.ID},
		},
	}
}

func inputSummary(in DreamInput) string {
	if in.Subject != "" || in.Predicate != "" || in.Object != "" {
		return strings.TrimSpace(in.Subject + " " + in.Predicate + " " + in.Object)
	}
	if in.Content != "" {
		runes := []rune(in.Content)
		if len(runes) > 96 {
			return string(runes[:96])
		}
		return in.Content
	}
	return in.Type + " " + in.ID
}

func compactSubject(in DreamInput) string {
	if in.Subject != "" {
		return in.Subject
	}
	if in.Content != "" {
		parts := strings.Fields(in.Content)
		if len(parts) > 0 {
			return parts[0]
		}
	}
	return in.Type
}

func clamp01(v float64) float64 {
	switch {
	case v < 0:
		return 0
	case v > 1:
		return 1
	default:
		return v
	}
}
